[2주차] 숫자 야구 게임 MVC 패턴 적용 제출합니다
Greedy-FrontEnd-Study/javascript-baseball-precourse pull request #10
Opened 2024-10-01 14:12 UTC by ye6194

안녕하세요!

저는 1주차 미션에서 baseballGame() 함수를 썼지만 이번에 BaseballGame 클래스로 바꿨답니다.
예전에 간단한 예제를 보며 클래스를 공부한 적은 있지만 실제로 써본건 처음이라 쉽지 않았어요...

이번에 MVC 패턴으로 바꾸기 위해 여러 함수가 생겼어요.
대부분 view를 구현하기 위해 만들어진 함수들인데 제가 view, controller, model로 잘 나눈건지 저도 확신이 안서네요😂

일단 실행은 index.js에서 BaseballGameController를 호출하면서부터 시작합니다. 순서가 좀 복잡해요...!!

그럼 잘 부탁드립니다.

2024-10-02 08:45 UTC, Songhyejeong reviewed
안녕하세요 예은님! 👋🏻

코드 잘 읽었습니다 :)

코드가 전체적으로 깔끔해서 읽기 편했던 거 같아요!
그리고 예은님이 많이 생각하셨던 노력이 보였던 거 같습니다..!

저도 예은님처럼 MVC에 대해서 아직 확신이 서지 않더라고요 ..  
그래서 예은님과 생각을 공유해보면서 정리해나가고 싶어요!

- 메시지 출력함수를 model에서 관리하는 거에 대해서는 어떻게 생각하실까요?
    
    저는 2주차 노션에 있는 MVC 패턴 구현 요구사항 중에 _**View는 Model에만 의존한다.**_ 라는 조건에서 View에 전달될 값들이 model에서 관리 되는 것이 좋겠다고 생각했어요!
model에서 메시지를 관리하고 controller는 view에게 데이터를 전달하는 역할만 수행할 수 있게 하는건 어떨까요?

- 또한 사용자 입력 값도 계속 바뀌고 관리, 검증해야하는 데이터라고 생각해서 모델에 넣었는데 예은님의 생각도 궁금하네요 👍 

이번주차 미션도 수고많으셨습니다! 감사합니다..!

2024-10-02 08:45 UTC, Songhyejeong commented on src/controller.js
> +    const userString = String(userInput);
문자열로 바꾸는 toString은 들어봤는데 String은 처음 들어보는데 어떨 때 사용하는 걸까요?

2024-10-02 08:45 UTC, Songhyejeong commented on src/controller.js
> +    if (strikeCnt === 0 && ballCnt !== 0) return `${ballCnt}볼`;
정답 메시지 출력하는 부분 간결하고 보기 좋은 코드 같아요!

2024-10-02 08:45 UTC, Songhyejeong commented on src/index.js
> +submitBtn.addEventListener("click", (event) => baseballGameController.showGameResult(event));
저는 이 이벤트 실행 함수의 위치에 대해서 고민했었는데 index.js에 넣어주셨네요 👍

2024-10-02 08:45 UTC, Songhyejeong commented on src/model.js
> +      let pickedNumber = MissionUtils.Random.pickNumberInRange(1, 9);
예은님 혹시 const와 let의 차이에 대해서 들어보셨나요?? 
const는 재할당시 오류가 발생해서 값이 의도치 않게 바뀌는 것을 막아주는 장점이 있대요! 
이 부분에서 pickedNumber은 재할당되지 않으니, const를 사용해보시는 건 어떨까요..?

2024-10-02 08:45 UTC, Songhyejeong commented on src/validate.js
>  // userInput의 유효성 검사를 하는 함수
함수를 간단하게 두 개로 나누신거 좋은거 같아요 👍 
함수명이 조금더 각자 하는 일을 명확하게 드러내면 좋을 거 같네요!
그리고 두개의 함수가 중복되는 부분이 있어서, true, false를 반환하고 controller에서 공통으로 alert를 실행시켜도 좋을 거 같아요!

2024-10-02 08:45 UTC, Songhyejeong commented on src/view.js
> +  submitBtn.disabled = show;
버튼에 disabled 속성이 있는 거 처음 알았어요! 👍

2024-10-02 08:45 UTC, Songhyejeong commented on src/model.js
> +  // 스트라이크, 볼을 세는 메서드
스트라이크, 볼을 세는 메서드 간결하고 보기 좋네요!!

2024-10-02 08:45 UTC, Songhyejeong commented on src/model.js
> +      if (!randomNumber.includes(pickedNumber)) randomNumber[i] = pickedNumber;
배열에 직접 값을 할당하는 것 대신 Array.push를 사용하는 것은 어떨까요 ,,? AirBnb [4.2](https://github.com/parksb/javascript-style-guide?tab=readme-ov-file#arrays--push)

2024-10-02 08:45 UTC, Songhyejeong commented on src/validate.js
>      inputField.value = ""; // 입력창을 비움
입력창을 비우는 코드가 controller에서는 clearInputField()라는 함수로 존재하던데 통일 시키면 더 좋을 거 같네요..!

2024-10-02 08:45 UTC, Songhyejeong commented on docs/test_result.png
👍

2024-10-03 13:16 UTC, ye6194 commented on src/controller.js
> +    const userString = String(userInput);
String도 문자열로 바꿀 때 사용하는 함수입니다!
toString은 객체만 쓸 수 있고, null이나 undefined이면 에러가 발생해요.
반만에 String은 객체가 아니어도 쓸 수 있고, null이나 undefined이어도 에러가 발생하지 않고 문자열로 변환돼요 ("null", "undefined")

2024-10-03 13:27 UTC, ye6194 commented on src/model.js
> +      let pickedNumber = MissionUtils.Random.pickNumberInRange(1, 9);
const는 한번만 할당되는 값, let은 재할당되는 값인건 알고 있었긴 했지만
저는 for문을 돌면서 계속 pickedNumber이 재할당되는 것으로 생각해서 let을 사용했어요.
그런데 for문에서도 const로 선언해도 되는 거였네요...! 덕분에 알아갑니다😊

2024-10-03 13:59 UTC, ye6194 commented on src/model.js
> +      if (!randomNumber.includes(pickedNumber)) randomNumber[i] = pickedNumber;
오 저도 1주차에 컨벤션 공부했었는데 이 부분은 놓쳤었나봐요. 수정했습니다! 왜 이렇게 하는지 이유도 궁금하네요.

2024-10-03 14:08 UTC, ye6194 commented on src/validate.js
>      inputField.value = ""; // 입력창을 비움
그렇게 수정했습니다!!

2024-10-03 15:08 UTC, Indigochi1d commented
안녕하세요 예은님!
이번 MVC미션 어떠셨나요...?
1주차의 just구현과 달리 디자인 패턴 적용이 조금은 난해하셨을거라고 생각해요! 그럼 이제 리뷰를 시작해보도록 하겠습니다!

2024-10-03 16:14 UTC, Indigochi1d requested changes
예은님 2주차도 코드 만드시느라 고생 많으셨어요😢 
이번 MVC미션을 수행하시면서 내가 이걸 왜 써야하지? 라는 생각을 하셨을 것 같아요.
그래서 예은님께 묻고 싶은게 있습니다!

1 .MVC와 같은 디자인 패턴을 사용하면 어떤 장점들을 얻을 수 있을 것이라고 생각하시나요? 왜 사용할까요?
2. MVC 패턴을 사용하시면서, 혹시 "불편하셨던 점이나, 이런 점은 단점으로 다가왔다" 라는 게 있으셨다면, 공유해 주실 수 있나요?

이미 좀 늦었지만 스터디 시간에 공유하면 좋을 것 같아요!
이렇게 리뷰를 남겨보았는데 혹시 제 생각과 다르게 생각하신게 있다면 얼마든지 다시 알려주세요! 
이번주도 정말 고생많으셨고 다음 미션부터는 React로 들어가게 될텐데 그땐 예은님께 많이 쉬울거에요! 고생하셨고 이따 스터디때 봐요~

2024-10-03 16:14 UTC, Indigochi1d commented on src/controller.js
> +  }
우선 이 로직은 Model에 있는게 더 적합해보여요! 
## play메서드의 기능
1️⃣ user로부터 input을 받는다. ➡️ controller
2️⃣ strike ball 등 결과를 판별한다 ➡️ model (판별하는 로직은 모델에서 수행되어야 할 것 같은데 예은님 생각은 어떠신가요?)

그래서 user로부터 input을 받을때 controller에서 받는 코드와 정답을 판별하는 코드 이렇게 나눠져야 할 것 같습니다!

2024-10-03 16:14 UTC, Indigochi1d commented on src/validate.js
> +  const isValid = /^[1-9]{3}$/.test(userInput); // 1~9로 이루어진 3자리 숫자인지 확인
정규표현식을 사용하셨군요!! 👏🏻

2024-10-03 16:14 UTC, Indigochi1d commented on src/validate.js
이렇게 validate method들을 분리해놓으셔서 읽기 편했던 것 같아요!

2024-10-03 16:14 UTC, Indigochi1d commented on src/view.js
view를 잘 작성해주셨네요!! view의 의존과 데이터 조작에 대해서 빡빡하다고 느끼셨을텐데 깔끔하게 잘하신 것 같습니다😄

2024-10-03 16:14 UTC, Indigochi1d commented on src/index.js
> +submitBtn.addEventListener("click", (event) => baseballGameController.showGameResult(event));
저는 이 이벤트 실행함수가 Controller에 있어야한다고 생각했는데 @ye6194 님과@Songhyejeong 님은 어떻게 생각하시나요❓

2024-10-04 16:59 UTC, ye6194 commented on src/model.js
> +    }
숫자를 리턴해야 해서
```
// computerInput(정답)을 얻는 메서드
  getComputerInput() {
    let computerInput = 0;
    let count = 0;

    while (count < 3) {
      const pickedNumber = MissionUtils.Random.pickNumberInRange(1, 9);

      if (!String(computerInput).includes(String(pickedNumber))) {
        if (count === 0) computerInput += pickedNumber * 100;
        else if (count === 1) computerInput += pickedNumber * 10;
        else computerInput += pickedNumber;  // count === 3
        count++;
      }
    }
    console.log(computerInput);
    return computerInput;  // 세 자리 정수 반환
  }
```

이렇게 바꿔봤는데 이건 어떠신 것 같나요?? 코드가 오히려 길어지긴 했네요ㅠ

2024-10-04 17:00 UTC, ye6194 commented on src/controller.js
> +  }
수정했습니다!

2024-10-04 17:03 UTC, ye6194 commented
다시 생각해보니 ```submitBtn.addEventListener("click", (event) => baseballGameController.showGameResult(event));``` 이 부분은 사용자의 클릭을 받아야 해서 controller에 있는게 맞는 것 같네요. 수정했습니다.

2024-10-06 08:38 UTC, merged