[2주차] 숫자 야구 게임 MVC 패턴
Greedy-FrontEnd-Study/javascript-baseball-precourse pull request #11
Opened 2024-10-01 15:34 UTC by bae-kh

안녕하세요!

이번 과제를 하면 MVC패턴을 처음 보게되었습니다.
처음 생각할 때 1주차 때 짜논 기능들이 어디에 배치되어야하는지 생각해보았습니다.
그래서 각 기능들을 model view controller에 알맞은 위치로 옮기고 controller에서 실행이 되도록 코드를 짰습니다.
막상 짜고 보니까 먼가 이상한거 같긴한데 어떤 방식이 정답인지 잘 모르겠어서 처음 생각한 방식으로 해봤습니다.
많이 부족하겠지만 여러 코멘트와 피드백 해주시면 감사하겠습니다..!
잘부탁드립니다!!

2024-10-02 04:56 UTC, gogo1414 reviewed
안녕하세요, 강현님!
리뷰어 김준수입니다😊

강현님이 작성해주신 코드 모두 잘 읽어봤어요! 저는 계층 적용을 할 때 고민을 너무 많이 해서 조금 힘들더군요... 강현님은 어떠셨나요??

코드 내에서 아직 분리가 제대로 적용되지 않은 것으로 보였어요! `index.js`의 내부에 존재하는 `function`이 다른 `model`, `view`, `validate`, `controller` 중에 존재하는 것을 보여요! 
그리고 함수명과 메서드명을 좀 더 명확하게 하시면 어떨까 하는 생각이 드네요! 메서드 네이밍 같은 경우는 의천님이 작성해주신 [**메서드 시그니처**](https://github.com/Greedy-FrontEnd-Study/javascript-baseball-precourse/pull/3#discussion_r1777893710)에 대한 설명과 다른 외부 사이트를 참고하셔서 꼭 한번 읽어보시길 추천드립니다😊

2024-10-02 04:56 UTC, gogo1414 commented on src/model.js
> +  else if (UserNum[2] == ComNum[0] || UserNum[2] == ComNum[1]) ball+=1;
`strike`, `ball` 의 값을 증가시켜 야구공 게임의 결과를 판단하기 위한 로직으로 보이는데, `if`와 `else if`에 값을 비교하는 조건의 방식이 아닌 다른 방식으로 구현해볼 수 있진 않을까요? 
저 같은 경우는 `Set` 또는 `includes`와 같은 다른 방식들을 사용했는데, 강현님도 한번 사용해보시면 더 깔끔하게 코드를 작성하실 수 있을거 같아요!

2024-10-02 04:56 UTC, gogo1414 commented on src/controller.js
> +  let UserNum = document.querySelector("#user-input").value;
사용자의 입력 값을 `let`으로 받은 이유가 있으실까요? 
여기서 받은 이후에 다른 곳에서 입력 값의 변경(타입 변경은 제외)이 이루어지지 않고 있는 것으로 보여서 궁금하네요!!

2024-10-02 04:56 UTC, gogo1414 commented on src/controller.js
> +let ComNum = getRandomNum(); //컨트롤러
아래 사용자의 입력에 대해 적은 리뷰와 동일하게 어떤 이유에서 이렇게 사용하셨나요??

2024-10-02 04:56 UTC, gogo1414 commented on src/index.js
> +        break;
`comNum`을  `return` 하고 있기 때문에 `break`는 없어도 괜찮을거 같아요!

2024-10-02 04:56 UTC, gogo1414 commented on src/index.js
다른 `js` 에 존재하는 메서드들이 index.js에 중복으로 존재하고 있는 것으로 보여요

따라서, index.js나 다른 파일들의 코드를 비교하셔서 중복된 코드를 삭제해주시는게 좋을거 같아요!

2024-10-02 04:56 UTC, gogo1414 commented on src/view.js
> +    document.querySelector("#result").innerHTML = `<div style="font-size: 20px;"><b>🎉정답을 맞추셨습니다🎉</b></div><br>게임을 새로 시작하시겠습니까?`;
해당 부분에서 `inndeHTML`를 사용했을 경우 발생할 수 있는 XSS의 공격에 대해서 알고 계시나요?? 
저도 1주차 미션에서 의천님께 받은 [리뷰](https://github.com/Greedy-FrontEnd-Study/javascript-baseball-precourse/pull/3#discussion_r1778091040)를 통해 알게 되었는데, 한번 들어가셔서 읽어보시면 도움이 되실 것 같습니다!

2024-10-02 04:56 UTC, gogo1414 commented on src/model.js
> +  if (ball > 0) return `${ball}볼`;
위에서 `strike`, `ball`을 판단 한 후 판단한 값을 이용해 결과를 반환하는 것으로 보이는데요!

이는 분리할 수 있지 않을까요??

2024-10-02 04:56 UTC, gogo1414 commented on src/view.js
> +  document.getElementById('game-restart-button').style.display ='none';	//뷰?
변수명을 지정하지 않고 `document`를 바로 받아서 버튼을 숨기게 되면 코드를 읽을 때 어떤 의미인지 단번에 파악하기 어렵지 않을까요??

2024-10-02 04:56 UTC, gogo1414 commented on src/controller.js
> +  let UserNum = document.querySelector("#user-input").value;
`let`, `const` 각각의 의미와 그 차이점에 학습해보시면 좋을거 같아요!!

제가 공부할 때 참고했던 사이트입니다! [var, let, const](https://www.freecodecamp.org/korean/news/var-let-constyi-caijeomeun/)

2024-10-02 04:56 UTC, gogo1414 commented on src/model.js
저는 mvc 패턴을 적용할 때 모두 `class`로 적용시켜서 진행했는데 `function`으로 적용시켜서 진행하셨네요!
해당 방법도 function의 의미가 분명하다면 사용하기 좋은 방법 같아요👍

2024-10-02 08:39 UTC, bae-kh commented on src/model.js
> +  else if (UserNum[2] == ComNum[0] || UserNum[2] == ComNum[1]) ball+=1;
좋은 피드백 감사합니다. 저도 막상 짜놓고 보니 가독성이 떨어져서 고민했었는데 set이나 includes를 사용해서 적용해봐야겠네요.

2024-10-02 08:40 UTC, bae-kh commented on src/controller.js
> +  let UserNum = document.querySelector("#user-input").value;
사실 let const에 대해서 잘모르는 상태로 변수만 보이면 let으로 적었던 거 같아요. 자료주셔서 감사합니다. 공부해보고 수정해봐야겠네요!

2024-10-02 08:41 UTC, bae-kh commented on src/index.js
> +        break;
좋은 지적 감사합니다.

2024-10-02 08:44 UTC, bae-kh commented on src/index.js
제가 github에 대해 잘 몰라서 일어난 실수입니다. 이번에 2주차 과제를 할때 기존에 짜놓았던 index.js와 valdate.js를 삭제하고 model.js controller.js view.js를 생성했습니다. 그래서 전체 실행을 index.js 대신 controller.js로 하는 방식으로 짜고 제출했는데 github에 index.js랑 validate.js가 삭제된게 표시가 안돼서 혼동이 있었네요.. 
visual stdio에서 삭제하고 github에 삭제했다고 표시하는 방법 알려주시면 감사하겠습니다ㅠㅠ

2024-10-02 08:45 UTC, bae-kh commented on src/view.js
> +    document.querySelector("#result").innerHTML = `<div style="font-size: 20px;"><b>🎉정답을 맞추셨습니다🎉</b></div><br>게임을 새로 시작하시겠습니까?`;
좋은 지적 감사합니다. 더 공부하고 개선해야겠네요!

2024-10-02 08:49 UTC, bae-kh commented on src/model.js
> +  if (ball > 0) return `${ball}볼`;
네 저도 비슷한 생각을 했었는데 분리해서 얻는 이점을 잘모르겠어서 이런식으로 두었습니다.
분리하면 함수도 많아지고 이로인해 코드가 길어져서 안 좋지 않을까라는 생각을 했었습니다.
혹시 분리하면 얻는 이점이 있을까요??

2024-10-02 09:00 UTC, bae-kh commented on src/view.js
> +  document.getElementById('game-restart-button').style.display ='none';	//뷰?
아 듣고 보니 그런 문제점이 존재하는지 알게되었습니다.
좋은 지적 감사합니다! 해결하기 위해 더 생각해봐야겠네요

2024-10-02 09:01 UTC, bae-kh commented on src/model.js
사실 class를 잘 다루지 못해서 먼저 떠오른 방법인 fuction으로 적용시켜서 진행했던 것 같습니다..!
좋은 코드리뷰 감사합니다!!

2024-10-02 11:51 UTC, gogo1414 commented on src/model.js
> +  if (ball > 0) return `${ball}볼`;
혹시, 단일 원칙 책임에 대해서 알고 계실까요?? 의천님이 설명해주시는 메서드 시그니처에 대한 설명에도 등장하는 단어인데요!

설명 글에 보시면 아래와 같이 말씀해주고 계세요!
"각 함수가 하나의 역할만을 수행하고 있어요. 즉 단일 책임 원칙을 잘 준수하고 있어요."

강현님은 함수가 많아져서 코드가 길어지기 때문에 가독성이 떨어지지 않을까 걱정하고 계시는데, 아래의 예시를 살펴볼까요?

1. 하나의 함수에서 5개의 역할을 맡아서 실행되는 경우
2. 5개의 함수가 각각의 역할이 명확하게 맡아 실행되고 경우

1번의 경우에는 5개의 역할을 하나의 함수에서 하고 있기 때문에 함수명에서 5개의 역할을 모두 설명하기 어렵고, 함수에 작성되어 있는 코드를 모두 읽어야 로직을 이해할 수 있어요(이해를 못하는 경우도 생기고요🥲)

2번의 경우 각 함수가 하나의 역할을 맡고 있기 때문에 함수명에서 어떤 역할을 맡고 있는지 설명하는 일이 매우 쉬워요! 코드를 읽지 않아도 어떤 역할을 맡고 있는 지 이해할 수 있고요!

제 설명이 부족할 수 있어서 외부의 블로그 글을 찾아봤어요! 한번 참고해보시면 좋을 것 같네요!

[단일책임원칙](https://inpa.tistory.com/entry/OOP-%F0%9F%92%A0-%EC%95%84%EC%A3%BC-%EC%89%BD%EA%B2%8C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-SRP-%EB%8B%A8%EC%9D%BC-%EC%B1%85%EC%9E%84-%EC%9B%90%EC%B9%99)

2024-10-02 11:57 UTC, gogo1414 commented on src/index.js
말씀 해주신게 vs code에서는 index.js, validate.js 파일 삭제를 진행했는데, github에 수정한 파일을 올렸을 때 반영이 안되고 계시는거죠??

2024-10-02 11:57 UTC, gogo1414 commented on src/index.js
`git status` 명령어를 통해 수정한 파일을 확인해볼 수 있어요!

자세한 문제 해결은 저도 지식이 얕아 직접 봐야 해결이 가능할 것 같아요..! 디스코드에 한번 문의 해보시는게 어떨까요??

2024-10-04 12:37 UTC, wzrabbit requested changes
@bae-kh  👋🏻 

안녕하세요, 강현님! 저는 그리디의 외부 리뷰어를 맡은 김의천이라고 합니다. 만나뵙게 되어 반가워요 😊

<img src="https://github.com/user-attachments/assets/e76c64e2-2ddc-4f00-8912-ff09a5df7a4e" width="500px" />

우선 수고하셨다는 말씀을 전해드리고 싶어요. 이제 막 JavaScript를 입문하신 것으로 알고 있는데, 입문하시자마자 하나의 제품을 구현해 보는 것도 모자라 MVC 패턴으로 리팩터링까지 해 보는 작업은 결코 쉬운 작업이 아니에요. 정말 찾아보고 신경써야 하는 부분이 많죠. 수고 정말 많이 하셨습니다. 🎉 

강현님이 이번 리뷰를 통해 많이 성장하실 수 있도록, 이번 리뷰에서는 제가 핵심적이라고 생각하는 부분 위주로, 코멘트를 단계별로 드려보도록 할게요!

## 1️⃣ 미션의 요구 사항 충족하기
우선, 작성하신 코드에서는 테스트가 실패하는데요, [1주차 리뷰](https://github.com/Greedy-FrontEnd-Study/javascript-baseball-precourse/pull/5) 에서 이미 이에 대해 이야기를 나누신 것 같고, 테스트의 실패 원인이 밝혀지지 않은채로 1주차의 리뷰가 끝난 것 같아요. 제가 테스트를 실행시켜 보았을 때는 테스트가 끝나지 않고 **무한 루프**가 발생했었어요.

테스트 실패 이유를 저도 찾아보고 싶었어서 디버깅해 보았고, 그 결과 테스트의 실패 원인은 아래와 같았습니다.
- 테스트에서 기대하는 `MissionUtils.Random.pickNumberInRange()` 의 사용법과 강현님의 사용법이 서로 일치하지 않았어요.

구체적으로는,
1. **테스트에서는 개발자가 `MissionUtils.Random.pickNumberInRange()`를 이용해 한 자리 수씩 가져올 것**이라고 생각하고 그에 대비해서 테스트가 짜여있고, 강현님께서는 `MissionUtils.Random.pickNumberInRange()` 한 번으로 세 자리 수를 한꺼번에 가져오도록 구현해 주셨어요.
2. 강현님께서는 `while` 문을 사용하셔서 잘못된 값이 입력으로 들어오면 다시 수를 입력받도록 구현해 주셨는데, 테스트대로라면 한 자리 수씩만 입력으로 들어와 `while` 문이 종료되지 않아요.
3. 그 결과 무한 루프가 발생하여 결과가 나오지 않아요.

테스트 통과를 위해, 아래의 요구사항을 드리고자 해요:
- `MissionUtils.Random.pickNumerInRange` 함수를 **한 자리 수**를 가져오는 데 사용해주세요.
- 첫 번째 호출에서 얻은 수를 백의 자리 수, 두 번째 호출에서 얻은 수를 십의 자리 수, 그리고 세 번째 호출에서 얻은 수를 일의 자리 수로 결정해 주세요.

1, 2주차에서 채점에 사용되던 테스트의 구체적인 원리가 궁금하시거나, 테스트 실패 원인에 대해 더 자세한 정보를 얻고 싶으신 경우 GREEDY 디스코드 서버의 `#개발-질문`에 있는 "cypress 테스트가 제대로 되지 않는 이유" 답변을 참고해 주시면 도움이 되실 거에요.

요구사항대로 기능을 정확하게 구현하는 것은 굉장히 중요하니, 2주차에서는 꼭 테스트에 성공해서 멋지게 끝내보자고요! 💪🏻 

## 2️⃣ MVC
이번 주차의 미션에서 다룬 메인 주제이죠! 

우선 리팩터링해 주신 코드에 대한 소감을 남겨드리자면, 모델, 컨트롤러, 뷰의 형태로 역할별로 코드가 잘 분리되었다고 생각하고 있어요. 👍🏻 
- 모델은 입력값을 검증하고, 숫자야구 게임의 결과를 판단하는 등 자신의 비즈니스 로직만을 잘 수행하고 있어요.
- 뷰 역시 컨트롤러로부터 데이터만 받아 사용자와 상호작용을 하고 결과를 사용자에게 보여주는 등 자신의 역할만을 잘 수행하고 있어요.
- 그리고 전반적인 프로그램의 제어를 컨트롤러가 잘 조율해 주고 있었어요.

이렇게 역할은 잘 나눠주셨는데, 혹시 MVC 패턴을 준수하며 리팩터링을 하시면서 어떤 생각을 해 주셨을 지 궁금해요. 아래의 두 질문을 강현님께 드리고자 해요:

1. MVC 패턴으로 코드를 리팩터링하면서 느끼신 소감을 말씀해 주시겠어요? 코드가 깔끔해지는 느낌이 들었다는 긍정적인 소감도 좋고, 오히려 코드가 복잡해진 것 같은 솔직한 소감도 좋습니다.
2. 사실 가장 중요하다고 생각하는 질문인데, MVC 패턴을 떠나 이러한 디자인 패턴들은 어떤 장점을 가져다주기 위해 등장했다고 생각하시나요?


## 3️⃣ 클린 코드를 위한 노력
클린 코드의 중요성은 이미 잘 알고 계실 거라는 생각이 들어요. 그도 그럴 것이, 클린 코드를 강조하는 좋은 글들은 이미 많이 있고 개발은 혼자보다는 여럿이서 할 일이 굉장히 많다는 점을 잘 알고 계실 것이기 때문이에요. 하다못해 혼자 개발을 하더라도, 규모가 가면 갈수록 커지는 일이 태반이고 1주일만 지나면 내가 짰던 코드를 내가 못 알아보는 일이 생기기도 하거든요 😇

하지만 미션에 제시된 Airbnb 컨벤션 문서는 솔직히 너무 길고 막연하다고 생각될 수도 있다고 충분히 생각하고 있어요. **39**개의 대주제와 몇 백개의 소주제를 다 보는 것은 저한테도 무리에요. 이 컨벤션을 한 번에 지키는 것은 분명 가혹할 거에요.

그렇기에, 저는 클린 코드를 위해 입문하는 입장에서 준수하기 좋은 **일관성**을 챙기는 방법, 그리고 당장 실천하시기에 용이한 항목부터 추천드려 보고자 해요. 지금 알려드리는 내용은 Airbnb 컨벤션에 나와있을 뿐만 아니라, JavaScript를 사용하는 대부분의 개발자분들이 준수하시는 컨벤션이에요.

아래의 내용들을 먼저 준수해 보시면 좋을 것 같습니다. 이 내용들은 앞으로의 미션에서도 반영을 부탁드리며, 이번 미션에서 시간이 남으신다면 반영해 보시기 바랍니다.

### 1️⃣ JavaScript에서의 이름을 짓는 규칙
- 함수, 변수, 오브젝트의 이름을 지으실 때는 **카멜 케이스(`camelCase`)를 사용해 주세요.
  - 카멜 케이스란? 단어를 구분할 때마다 대문자를 사용하되, 첫 단어는 소문자로 시작하는 변수 명명법이에요. `fruit`, `menuColor`, `getSingleRoundBaseballResult`

- 클래스의 이름을 지으실 때는 **파스칼 케이스(`PascalCase`)를 사용해 주세요.
    - 파스칼 케이스란? 단어를 구분할 때마다 대문자를 사용하고, 첫 단어 또한 대문자로 시작하는 변수 명명법이에요. `Lotto`, `BaseballGame`, `DateFormatter`

- 상수의 이름을 지으실 때는 **대문자를 사용하는 스네이크 케이스(`SNAKE_CASE`)를 사용해 주세요.
    - 스네이크 케이스란? 단어를 구분하기 위해 언더바(`_`)를 사용하는 변수 명명법입니다. JavaScript에서의 상수명을 지을 때는 각 단어를 모두 대문자로 적습니다.
    - JavaScript에서의 상수란 개발자가 **프로그램 실행 중 절대 변하지 않을 것이라고 신뢰할 수 있는** 불변값을 의미합니다. `PI`, `MAX_USERS_PER_ROOM`, `BASE_URL`

### 2️⃣ 특별한 이유가 없는 한 코드의 작성 규칙을 통일해 보세요.
- 예를 들기 쉬운 항목은 세미콜론입니다. 세미콜론을 사용하지 않는 방법과 사용하는 방법 모두 유효하며 개발자의 취향에 따라 달리할 수 있지만, **사용한다면 모든 코드에서 사용하고, 사용하지 않는다면 모든 코드에서 사용하지 않는 것** 은 지켜져야 하는 사항입니다.

3️⃣ 변수, 함수 등 무언가의 이름을 지을 때에는 기능이 잘 드러나는 자세한 이름을 고민해 보세요.
- 이름이 길어지는 것은 나쁜 것이 절대 아닙니다. 길더라도 그게 의도를 잘 드러내기 위한 방법이라면 적극 사용해 보세요. `getRestaurantSearchResultByRegion`
- 주석을 사용해 코드를 설명하는 것도 좋은 방법이지만, 그 이전에 주석이 없더라도 이해하기 쉬운 코드가 우선이라고 생각합니다.

위의 세 종류의 코멘트에 대해서 중점적으로 생각해 보셨으면 좋겠어요. 이외에도 코멘트를 몇 개 달아드렸지만 시간이 촉박하시면 부분적으로 반영해주셔도 괜찮습니다. 중요한 것부터 해 보자고요! 💪🏻

2024-10-07 08:05 UTC, bae-kh commented on src/model.js
> +  if (isNaN(Number(input)) || input.includes("0")|| setinput.size !=3 || input.length !== 3) {
1. ===은 ==와 다르게 타입까지 동일한지 판별할 때 사용하는걸로 알고 있습니다.
2. 원래 모든 등호 관련 코드를 ===나 !==로 통일하려고 했는데 깜빡하고 !=로 적은 것 같습니다. ===이 ==보다 좀 더 정확하지 않을까 생각해서 통일하려고 했습니다!

2024-10-07 08:11 UTC, bae-kh commented on src/model.js
> +  }
넵 리뷰 감사합니다!

2024-10-07 08:15 UTC, bae-kh commented on src/model.js
> +    let ComNum = MissionUtils.Random.pickNumberInRange(100,999);
리뷰주신 내용 듣고 MissionUtils.Random.pickNumerInRange 함수를 한 자리 수를 가져오는 데 사용했더니 cypress 테스트 통과했습니다!
![스크린샷 2024-10-07 171512](https://github.com/user-attachments/assets/1fb93d72-a74c-4d47-9dad-033eccbca98b)

2024-10-07 08:26 UTC, bae-kh commented on src/controller.js
> +});
의문이 들긴했습니다. 왜 굳이 모델은 컨트롤러를 거치고 뷰와 소통하는 걸까? 제가 생각한 결론은 뷰와 모델이 컨트롤러없이 소통하면 각자의 역할이 모호해지고 이로 인해서 mvc패턴의 장점인 유지보수가 힘들어질 것이다 라고 생각했습니다.

2024-10-07 08:28 UTC, bae-kh commented on src/model.js
> +      break;
다시보니 break가 될 가능성은 없어보이네요.
break는 반복문 같은 문법을 멈추는 예약어이고
return은 함수의 실행을 종료하고 선택적으로 값을 정해서 반환하는 예약어입니다.

2024-10-07 08:57 UTC, bae-kh commented
리뷰어님 좋은 리뷰 감사합니다!!
먼저 리뷰해주신 cypress test 안되는 점 이를 수정했더니 cypress 통과했습니다. 저번주부터 계속 테스트가 실행도 안돼서 애먹었는데 이런 문제점이 있었군요..

이번 과제를 처음 시작할 때 왜 MVC패턴을 사용해야되는지 이해를 못한체로 시작했습니다. 굳이 이미 짠 코드를 여러 요구사항을 맞추면서까지 나눠야하는지 몰랐습니다. 막상 기능별로 나눠서 짜보니 어느정도 납득이 되었습니다. 이렇게 기능별로 나눠서 짜두면 나중에 오류가 났을 때 어디서 오류가 났는지 빠르게 알 수 있겠다 싶었습니다. 이번 코드는 짧은 편이지만 긴 코드를 나누지 않고 짜면 오류를 찾는데 매우 오래 걸리겠다라는 생각을 하면서 코드 유지보수에 장점이 있구나라고 느꼈습니다.

클린코드에 관한 리뷰 잘봤습니다! 항상 코딩할 때 어떤 식으로 해야 클린 코드인지를 잘 몰라서 매번 함수나 변수 등 이름을 지을 때 제각각인 형태로 코딩했습니다. 다음부터는 이에 유의해서 코딩해야겠네요! 이번 과제 리뷰내용 보고 수정했습니다!

좋은 리뷰 감사합니다!

2024-10-08 16:43 UTC, wzrabbit approved these changes
@bae-kh 👋🏻 
코멘트를 드리는 시점에는 바쁘게 3주차 미션을 구현하고 계시겠군요!

코드 확인해 보았고, 말씀드렸던 여러 개선사항들을 잘 반영해 주신 것 확인했습니다 👍🏻 상당히 긴 코멘트를 드렸는데 끝까지 따라와주셔서 감사할 따름입니다. 달아드린 코멘트들은 천천히, 그러나 점차적으로 꾸준히 개선해 나가보시면 좋을 것이라고 생각합니다.

**코드에서 사용되는 이름의 일관성 지키기**, **이름은 뜻이 명확하게 드러나도록 짓기**와 같이 **이름** 을 유독 강조해드린 이유는 클린 코드를 짜기 시작하는 개발자가 깊은 개발 지식 없이도 빠르게 개선을 할 수 있는 방법이면서, 효과도 굉장히 큰 방법이기 때문이라고 생각하기 때문입니다. 이름을 명확하게 지으면 코드에 들어가는 의미가 풍부해지고, 그렇게 하면 이해하기 쉬운 코드를 짜실 수 있을 거라고 생각합니다.

<hr />

아래의 코멘트도 남겨주셨는데, 저도 제가 생각하는 바를 이야기해보고자 합니다.

> 의문이 들긴했습니다. 왜 굳이 모델은 컨트롤러를 거치고 뷰와 소통하는 걸까? 제가 생각한 결론은 뷰와 모델이 컨트롤러없이 소통하면 각자의 역할이 모호해지고 이로 인해서 mvc패턴의 장점인 유지보수가 힘들어질 것이다 라고 생각했습니다.

MVC에서 모델과 뷰가 즉시 소통하는 대신, 컨트롤러를 거쳐 소통하는 것은 컨트롤러가 프로그램이 진행되는 데 있어서 **제어권**을 가지고 있는 상황을 만들게 됩니다. 다르게 말하면, **뷰와 모델은 프로그램의 전체적인 흐름과 제어권에 좌우되지 않고, 자신이 해야 할 일만 집중할 수 있는** 형태를 지니도록 할 수 있습니다. 이는 말씀해주신 코멘트인 "**각자의 역할이 모호해지고**" 라는 단점을 상쇄시켜주는 상황이 된다고 할 수 있겠습니다. 강현님이 핵심적인 이유를 잘 짚어주셨다고 생각합니다.

저는 여기에 강현님이 좀 더 필요성을 이해하실 수 있도록, 그리고 유지보수가 어떻게 용이해지게 되는지를 부가적으로 설명해 보고자 해요.

<hr />

컨트롤러 뿐만 아니라, 뷰와 모델이 서로와도 긴밀하게 소통한다고 가정해 볼게요. 이 경우라면, 아래와 같은 그림이 되겠네요.

![image](https://github.com/user-attachments/assets/28233d29-63f3-4962-ac72-0a31a06ab877)

보시면 아시겠지만, 의존하는 관계가 마치 거미줄처럼 엮여 있는 상태에요. 여기까지는 그렇다 칠 수 있는데, 만약 **여기에서 모델이나 뷰 하나의 로직을 수정해야 한다면** 어떻게 될까요? 서로가 긴밀하게 의존하고 있는 상황이 되어, 아주 간단한 로직만을 수정하더라도 그 영향이 굉장히 많은 모듈들에 가게 될 거에요.

그렇게 되면 예상치 못한 변경이 일어나기도 더 쉬울 것이고, 버그가 발생하더라도 어디에서 발생했는지 파악하기 어려워져요. 이렇게 되면, 코드의 흐름을 파악하기 어려운 것은 물론 무슨 버그가 발생할 지 모르므로 아주 간단한 로직의 변경조차 어렵게 만들 거에요.

![image](https://github.com/user-attachments/assets/64d58f03-9514-4505-81bb-cbdb987b2312)

위와 같이 MVC 패턴을 준수하고, 모델과 뷰가 각각 컨트롤러하고만 소통하게 된다면, 당장은 말씀하신 불편함이 있을 수 있더라도, **빈번한 변경에 강하고, 버그가 발생하더라도 원인을 더 알아내기 쉬운 형태가 될 겁니다. 결과적으로 유지보수에 용이한 코드를 짤 수 있게 되는 거에요.**

덧붙여서, 이러한 형태는 **단위 테스트(Unit Test)** 를 하기에도 좋은 형태가 돼요. 단위 테스트란, 함수, 객체 등의 작은 단위로 진행하는 작은 규모의 테스트를 의미해요. 각 모듈에 대한 의존성이 줄어드니, 독립된 환경에서 테스트를 하는 상황에서도 유리함을 가져갈 수 있게 됩니다. 독립된 환경이라는 것은 테스트가 실패했을 경우 다른 외부 요인을 생각할 필요 없이 그 로직 자체 문제가 있다는 것을 쉽게 알아낼 수 있다는 것을 의미하거든요.

결론적으로, MVC 패턴을 비롯한 여러 디자인 패턴들은 **핵심 로직들을 서로 분리하고, 의존성을 줄이는 것을** 목표 중 하나로 두고 있다고 생각하는데요,
- 핵심 로직들 간의 의존도를 줄이면
- 코드를 빈번하게 수정하더라도 적은 위험부담으로 변경사항을 가할 수 있고
- 각자에게 주어진 역할만을 훌륭하게 수행해 코드를 이해하기 쉽게 만들고
- 버그가 발생하더라도 그 근원지를 알기 쉽도록 만들 수 있으므로
- **협업에 유리하고 유지보수에 용이한 프로젝트를 만들 수 있을 것이다**
를 기대할 수 있다고 생각합니다.

클린 코드를 짜기 위해 노력하고 개선할 수 있는 방법은 정말 많겠지만, 챙기고자 하는 궁극적인 목표는 결국 같습니다. 바로

**"읽고 이해하기 쉬운 코드를 작성해, 협업에 유리하고 유지보수에 용이한 프로젝트를 만들어 가자."**

이 가치를 앞으로도 잃지 않으셨으면 좋겠습니다.
미션 진행하느라 수고 많이 하셨습니다 👍🏻

2024-10-08 16:46 UTC, merged