[2주차] MVC 패턴 적용 미션 제출합니다.
Greedy-FrontEnd-Study/javascript-baseball-precourse pull request #12
Opened 2024-10-01 16:01 UTC by gogo1414

안녕하세요, 리뷰어님😊
이번 MVC 패턴 적용하시는 미션은 참 어떻게 해야할 지 난감했네요..

패턴 적용을 다 한 후 cypress test를 진행했었는데, test 자체가 진행되지 않는 에러가 생겨서 1주차 미션 완성 코드를 기점으로 오늘 코드를 다시 짜느라 시간이 너무 오래걸렸네요... 죄송합니다😭

사실 저는 백엔드 개발을 해왔기 때문에 익숙할 것이라고 생각했는데 언어가 다르다는 차이 하나로 제가 생각했던 방향(?)이 아닌 다른 방향으로 진행이 된 것으로 보여요.. 추가로, 타입을 명시할 수 없는 자바스크립트의 언어가 이번 미션을 진행하면서 확실하게 불편함으로 다가온게 컸답니다..

자세히 얘기를 드려보자면, MVC 패턴에 대해 범수님이 정리해주신 노션의 [2주차 스터디](https://www.notion.so/2-25685b99264649ce88a080dacbfd1a43?pvs=4)에서 model을 보시면 "무엇을 해야할 지 정의해야한다." 라고 되어 있는데, 무엇을 해야할 지 정의하기 전에 완전 초기 단계 어떤 값이 존재할 것이고 이를 통합해서 어떤 객체가 존재하는지 판단해보고 싶었어요.

`BaseballGame`이 객체가 될 수 있나(?) 라는 생각을 했을 때 저는 `BaseballGame`은 서비스라고 생각했어요. 그래서 `Baseball`이라는 객체 안에 각 필드(값)들이 존재하도록 생성해보고자 했는데, 이때 타입을 명시할 수 없는 점이 불편함으로 크게 다가왔고, 코드를 다 짠후 실행해보니 정상 작동이 되지 않더군요.. 그래서 기존 코드를 계층별로 분리하는 방식으로 진행하게 되었습니다... 아쉽네요🥲🥲🥲🥲

리뷰어님은 객체를 따로 만드셔서 진행하시는 것에 대해서는 어떻게 생각하시는지 궁금합니다!💡💡

2024-10-03 06:26 UTC, bae-kh commented
안녕하세요 준수님!
작성해주신 코드 잘 읽었습니다. 저는 이번 과제에서 클래스를 나눠서 사용하는게 쉽지않아서 잘 사용하지 못했는데 준수님 코드에는 되게 잘 적용되있어서 보면서 많은 영감을 얻었습니다! 
mvc 패턴에 대해서 되게 고심하면서 잘 적용하신게 보이는 코드같습니다!
2주차 미션하시느라 고생하셨습니다!

2024-10-03 06:45 UTC, bae-kh commented on src/controller/BaseballGameController.js
> +            const userNumbers = this.NumberUtils.inputConvertNumbers(userInput);
userinput을 정수형을 바꾸는 기능같은데 Number() 나 parseInt()함수를 이용하지 않고 따로 만드신 이유가 궁금합니다.

2024-10-03 06:45 UTC, bae-kh commented on src/model/BaseballGame.js
> +          }
includes 를 사용해서 깔끔하게 정리하신게 인상깊었습니다!

2024-10-03 06:45 UTC, bae-kh commented on src/utils/NumberUtils.js
> +        }
이런 식으로 표현할 수 있는지 처음 알았네요! 한 줄로 짧게 나타낼 수 있어서 좋은 코드 같아요!

2024-10-03 06:45 UTC, bae-kh commented on src/utils/NumberUtils.js
> +}
오 이렇게 number를 생성할 수도 있군요!

2024-10-03 06:45 UTC, bae-kh commented on src/view/BaseballGameView.js
> +    }
두 버튼을 묶어서 서로 반대로 표현하는 방식 되게 좋아보이네요!

2024-10-03 07:05 UTC, gogo1414 commented on src/utils/NumberUtils.js
> +        }
정규식 표현이라고 검색해보시면 많은 내용이 나와있어요!!

2024-10-03 07:05 UTC, gogo1414 commented on src/utils/NumberUtils.js
> +}
함수의 역할을 분리해서 진행하려고 노력했습니다ㅎㅎ🤗

2024-10-03 07:06 UTC, gogo1414 commented on src/view/BaseballGameView.js
> +    }
플로우 차트를 그려봤을 때 서로 반대되는 상황으로 진행되기에 이렇게 구성해봤어요!

2024-10-03 07:09 UTC, gogo1414 commented on src/controller/BaseballGameController.js
> +            const userNumbers = this.NumberUtils.inputConvertNumbers(userInput);
`parseInt()` 함수를 쓰게 되었을 때 문자열을 숫자로 바꿔주는 함수기 때문에 배열에 숫자를 하나씩 넣으려는 제 의도와는 벗어나서 사용하지 않고 따로 함수화해서 진행했어요!

2024-10-03 13:54 UTC, wzrabbit requested changes
@gogo1414 👋🏻 

또 뵙는군요!

2주차에서는 1주차의 숫자 야구 미션에서 로직은 그대로 유지하되, MVC 구조를 지니도록 코드를 리팩터링하는 작업을 진행해주신 것으로 알고 있어요.

코드를 살펴본 결과 전체적으로 코드는 깔끔하고 읽기 편했어요. 상호 리뷰이분께도 **메서드 시그니처** 많이 강조하시던데요...? ㅋㅋㅋ 그만큼 중요하게 생각하시는 것 같아서 다행입니다.

MVC 구조에 대해서는
- 숫자야구 게임의 핵심 로직을 Modal 파트로 잘 분리해주신 것을 보았고, `play()` 메서드에서는 캡슐화도 잘 지켜주신 점이 좋게 다가온 것 같아요. 
- 반면 컨트롤러에서 사용자의 인터페이스에 영향을 주는 View 로직이 몇몇 부분에서 보였던 것은 다소 아쉽게 느껴졌습니다.

물론 MVC를 구현하는 입장에서 개발자마다의 생각은 다양할 수 있음을 저도 이해해요. 그러니 말씀하시고 싶으신 의견이 있다면 공유해주시면 좋을 것 같습니다.

<hr/>

백엔드를 학습하다가 오셨을 테니 MVC 패턴이 무엇인지는 이미 잘 알고 계실 것이라는 생각이 듭니다. 아래의 두 질문을 해 준성님의 생각을 들어보고 싶어요.

1. MVC와 같은 디자인 패턴을 사용하면 어떤 장점들을 얻을 수 있을 것이라고 생각하시나요? 이런 거 왜 사용해야 될까요?
2. MVC 패턴을 사용하시면서, 혹시 "불편하셨던 점이나, 이런 점은 단점으로 다가왔다" 라는 게 있으셨다면, 공유해 주실 수 있나요?

리뷰 요청 시 이 두 질문에 답변해주셨으면 좋겠어요. 저도 제 생각을 공유해 드릴게요.

2024-10-03 13:54 UTC, wzrabbit commented on src/model/BaseballGame.js
> +    }
## 1️⃣ 

저는 이 부분의 코드가 **캡슐화**가 잘 적용된 코드라고 생각하고 있어요. 컨트롤러가 모든 정보를 들고 모델의 메서드를 일일이 모두 실행시키는 대신, 컨트롤러는 `play()` 만을 실행해 모델에게 일을 할 것을 **지시**하고, 그 이후 **모델 내에서 자신의 스스로 할 수 있는 일들은 자신이 스스로 수행한 후** 결과를 반환하고 있어요.

컨트롤러 입장에서 모델이 해야 할 일을 알 필요도 없고, 모델이 스스로 할 수 있는 일이라면 모델이 스스로 일을 하도록 내버려 두는 방식을 사용한다면, **의도치 않은 외부에서의 조작**을 방지할 수 있을 거에요.

그런 의미에서, 컨트롤러가 모든 걸 조작하고 모델이 수동적인 구조를 지니기보다는, 클래스의 장점을 살려 실행하는 측에서는 클래스에 **메시지만 보내는** 현재의 형태는 굉장히 좋은 것 같다고 생각합니다.

- **Tell, Don't Ask.** - 객체 내부의 데이터를 가져와서 처리하지 마세요. 객체에게 **메시지를 보내**세요.

클래스의 장점을 잘 활용하셨고 캡슐화를 잘 지키셨어요. 👏🏻 

## 2️⃣ 

위에서 챙기신 **캡슐화**의 장점을 더 JavaScript에서 무궁무진하게 활용하실 수 있도록, 팁을 하나 드릴게요.
JavaScript에서도 private method라는 것을 사용하실 수 있다는 것을 알고 계신가요? ES2019부터 생긴 기능인데, 멤버명이나 메서드명의 앞에 `#` 를 붙이는 것으로 private method으로 만들 수 있습니다.

```js
class Foo {
  #myPrivateVariable = [];

  #myPrivateFunction() {
    // Do something...
  }
}
```

이렇게 하면, 아예 물리적으로 외부에서 `#myPrivateVariable`, `myPrivateFunction` 을 사용할 수 없게 됩니다. 잘 활용하신다면 사용자가 의도치 않게 이 값이나 함수들을 조작 및 실행해 오작동하는 것을 방지할 수 있을 겁니다. 💪🏻 꽤나 강력한 기능입니다

Read: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Classes/Private_properties

2024-10-04 01:56 UTC, gogo1414 commented on src/controller/BaseballGameController.js
> +import BaseballGame from "../model/BaseBallGame.js";
오타였어요!! 저도 모르고 있었는데 감사합니다!

2024-10-04 03:05 UTC, gogo1414 commented on src/model/BaseballGame.js
> +        };
오, 신기하게 `let` -> `const`로 바꿔도 잘 작동되네요!

`strikeBallCounts` 라는 구조 할당이 변경되는게 아니라 안의 값들이 변경되기에 재할당이 아닌거 같은데 맞을까요...?

2024-10-04 04:27 UTC, gogo1414 commented on src/model/BaseballGame.js
> +            if (userNumbers[i] === this.computerNumbers[i])
제가 알기로 `==` 비교연산자의 경우 아래의 이미지와 같이 타입이 다른 1과 '1'을 같다고 표시해주기 때문에 타입까지 비교 가능한 `===` 연산자를 사용했습니다!

<img width="103" alt="스크린샷 2024-10-04 오후 1 26 42" src="https://github.com/user-attachments/assets/4dfa693e-6721-4c7c-b9ad-7b7d625b5543">

2024-10-04 04:30 UTC, gogo1414 commented on src/utils/NumberUtils.js
> +    }
오, 두 방법 모두 좋네요!
첫번째 방법대로 진행해서 코드를 더 단순화 해보겠습니다!

2024-10-04 04:31 UTC, gogo1414 commented on src/controller/BaseballGameController.js
> +        }, 1);
시간을 명시하지 않음으로써 자동으로 **최소 지연 시간**이 지정되는 방식인걸까요?? 좋은 방법으로 보여요!!

2024-10-04 04:31 UTC, gogo1414 commented on src/model/BaseballGame.js
> +    }
감사합니다🤗

2024-10-04 04:32 UTC, gogo1414 commented on src/model/BaseballGame.js
> +        console.log(this.computerNumbers);
엇 매번 제출할 때 마다 빼야지 했는데 여태 안빼고 있었네요..

2024-10-04 05:26 UTC, gogo1414 commented on src/controller/BaseballGameController.js
> +    }
한번, 사용자가 3스트라이크를 입력했을 때의 플로우 차트를 글로 간단하게 표현해보았어요!

사용자가 숫자 3개를 입력한다. (`click event` 발생) -> 야구공 게임 진행 -> 3스트라이크 판별 -> 게임 종료 -> 축하 메시지 출력 -> 버튼 토글

버튼을 토글시키는 것, 축하 메시지 출력 모두 `view` 계층과 연관이 밀접하다고 느껴지네요! 
축하 메시지 출력하는 것 자체를 `controller`가 아닌 `view` 계층으로 옮겨보도록 하겠습니다! 다만, 버튼을 토글 시키는 함수가 `view`계층에 존재하고 이를 `controller`에서 실행시키고 있는건데 조금 이상할까요??

2024-10-04 05:37 UTC, gogo1414 commented on src/model/BaseballGame.js
> +    }
자바스크립트내에서 `private method`를 만들 수 있다니 매우 좋네요! 보내주신 사이트 내에서 살펴보니 `static`도 존재하네요!

자바에서 사용되는 것들을 자바스크립트 내에서도 보게되니 참 반갑네요😊

2024-10-04 05:37 UTC, gogo1414 commented
> @gogo1414 👋🏻
> 
> 또 뵙는군요!
> 
> 2주차에서는 1주차의 숫자 야구 미션에서 로직은 그대로 유지하되, MVC 구조를 지니도록 코드를 리팩터링하는 작업을 진행해주신 것으로 알고 있어요.
> 
> 코드를 살펴본 결과 전체적으로 코드는 깔끔하고 읽기 편했어요. 상호 리뷰이분께도 **메서드 시그니처** 많이 강조하시던데요...? ㅋㅋㅋ 그만큼 중요하게 생각하시는 것 같아서 다행입니다.
> 
> MVC 구조에 대해서는
> 
> * 숫자야구 게임의 핵심 로직을 Modal 파트로 잘 분리해주신 것을 보았고, `play()` 메서드에서는 캡슐화도 잘 지켜주신 점이 좋게 다가온 것 같아요.
> * 반면 컨트롤러에서 사용자의 인터페이스에 영향을 주는 View 로직이 몇몇 부분에서 보였던 것은 다소 아쉽게 느껴졌습니다. 컨트롤러가 직접 View 로직에 간섭하기보다는 View에게 인터페이스를 대신 조작할 것을 부탁하는 방법은 없을까요?
> 
> 물론 MVC를 구현하는 입장에서 개발자마다의 생각은 다양할 수 있음을 저도 이해해요. 그러니 말씀하시고 싶으신 의견이 있다면 공유해주시면 좋을 것 같습니다.
> 
> 백엔드를 학습하다가 오셨을 테니 MVC 패턴이 무엇인지는 이미 잘 알고 계실 것이라는 생각이 듭니다. 아래의 두 질문을 해 준수님의 생각을 들어보고 싶어요.
> 
> 1. MVC와 같은 디자인 패턴을 사용하면 어떤 장점들을 얻을 수 있을 것이라고 생각하시나요? 이런 거 왜 사용해야 될까요?
> 2. MVC 패턴을 사용하시면서, 혹시 "불편하셨던 점이나, 이런 점은 단점으로 다가왔다" 라는 게 있으셨다면, 공유해 주실 수 있나요?
> 
> 리뷰 요청 시 이 두 질문에 답변해주셨으면 좋겠어요. 저도 제 생각을 공유해 드릴게요.

2024-10-04 16:56 UTC, wzrabbit approved these changes
@gogo1414 👋🏻 

리뷰들을 잘 반영하고 오셨군요! 특히 의문이 드는 코멘트에 대해서는 바로 반영하지 않고 리뷰어에게 질문을 던지시는 점도 좋았습니다.

질문에 대한 답변 먼저 진행하겠습니다.

## 질문/답변

> 3주차 스터디를 진행하면서 1번과 2번에 대한 답을 간단하게 적는 시간을 가졌었는데요! 여기에서는 그 답변을 조금 더 보충해서 작성해보도록 하겠습니다!

허걱... 범수님 리뷰도 봤습니다. 제가 던졌던 질문이 실제로도 스터디에 활용되었나요? 🍿 

> 우선, MVC 디자인 패턴을 얘로 들자면 협업을 할 때 디자인 패턴이 적용되어 있지 않다고 가정을 하면, 각자 맡은 역할에서 자기가 더 선호하는 방향으로 개발 코드를 작성을 할텐데 이는 협업을 할 때 서로의 진행성에 대해 이해를 어렵게 만들 수 있다고 생각해요.

> 반대로 만약 디자인 패턴이 적용되어 있다면, 개발자들은 하나의 방향으로 개발 코드를 작성할 수 있어요! 따라서 협업을 진행함에 있어 디자인 패턴을 적용하는 것도 중요 포인트 중 하나라고 생각합니다😊

네, 본인의 생각을 잘 설명해 주셨어요! 디자인 패턴이 큰 틀을 잡아주는 규약이나 도구로써도 충분히 활용될 수 있을 겁니다. 

> 2. MVC 패턴을 적용하면서 불편했던 점은 사실 패턴 적용 자체에 불편함이라기 보다 저는 자바스크립트 언어에 대한 이해도가 부족해서 적용하고 싶은 것을 바로 적용 못하는 점도 있었어요. 적용하더라도 코드 컨벤션에 어긋나게 적용이 되는 것도 문제점 중 하나라 이 부분이 꽤 불편하더군요..
> 다른 분들도 스터디 시간에 하신 얘기지만, 정말 간단한 로직 또는 서비스 구현이 목표라면 디자인 패턴을 적용하는게 리소스가 큰 작업이라고 생각이 드는 것도 불편한 점 중 하나네요!

머릿속은 무궁무진한데 언어로는 이걸 다 표현하시기가 아무래도 어려울 수도 있겠죠. 그 마음 충분히 이해합니다.
추가로, 이 미션을 진행하시면서
- 굳이 여기에 MVC를?
- 이렇게 작은 규모에는 MVC를 쓰기보다는 그냥 모듈 하나로 구현해도 문제 없지 않나?
라는 생각이 충분히 드셨을 수도 있을 겁니다.

규모가 작은 어플리케이션에는 디자인 패턴을 도입하지 않는 것이 오히려 나을 수도 있습니다. 이번에는 디자인 패턴과 친해지고 연습을 하셨다고 생각해 주세요. 
번지르르한 디자인 패턴을 사용하더라도 그 디자인 패턴을 이용했을 때 얻어갈 수 없는 장점을 놓친다면 그게 무슨 소용일까요?

> 저도 궁금한 점이 있는데요! 사용자의 입력 중 예외가 발생했을 경우 띄우는 `alert()` 의 경우 `controller` 에 있는게 좋을까요? 아니면, `view` 계층에 존재하는게 좋을까요?

꽤 고민되는 질문이네요. 저라면 아래의 방법을 따를 것 같습니다.
- `alert()` 한 줄로 간단하게 끝나는 함수이고, 사용이 빈번하지도 않는다면 Controller에 둔다.
- `alert()` 하나로는 간단하게 끝나지 않을 정도로 출력 로직이 조금이라도 복잡하거나, 혹은 출력할 메시지를 View만 알게 하고 싶은 경우 View에 둔다.

본래 출력 관련 로직은 View에 두고, Controller에서는 View에게 일을 시키는 것으로 MVC 패턴을 준수할 수 있다고 생각하고 있습니다. 그런데 `alert()`의 경우 단 한 줄의 로직이 끝이고, 이마저도 빈번하게 사용되는 경우가 아니라면 `alert()`를 사용하는 View 객체나 함수를 굳이 만들 필요성을 저로써는 느끼기 어려울 것 같습니다. 평범하게 View에 로직을 구현해두고 Controller에서 사용하더라도 한 줄의 View 로직을 부르는 함수는 써야 하고요.

그렇다고, 아래와 같이 억지로 View로 분리하자니 오히려 함수 하나를 과도하게 추상화한다는 느낌이 들기도 합니다. 이 경우에는 굳이 함수로 분리할 필요는 없어 보입니다.
```js
const printMessage = (message) => {
  alert(message);
};
```

따라서 출력 로직은 View에 두는 것을 지향하되 단순하고 간단하게 alert()를 사용하는 경우라면 저는 Controller에 두더라도 괜찮을 것이라 생각하고 있습니다.

준수님께서는 View 로직으로 alert 함수를 빼시는 선택을 하셨지만
1. `setTimeout`을 통해 `alert`이 진행되더라도 리페인팅을 차단하지 않기를 원하시는 의도가 담겨 있으며 추가적인 로직이 들어가는 것도 있고
2. 특정한 메시지를 View에서 관리하는 것도 있으므로

충분히 View로 뺄 필요성이 느껴진다고 생각합니다.

아래와 같은 형태는 기능이나 정보를 분리하고자 하는 의도가 느껴지기 때문에 저는 과도한 추상화라는 생각까지는 들지 않는 것 같습니다.

```js
const printGameOverMessage = () => {
  alert('Game Over! Try again.');
};
```

## 두 질문에 대한 제 생각
리뷰 때 제 생각도 공유드리겠다고 약속드렸었죠, 저도 제 생각을 공유해 보겠습니다.

> 1. MVC와 같은 디자인 패턴을 사용하면 어떤 장점들을 얻을 수 있을 것이라고 생각하시나요? 이런 거 왜 사용해야 될까요?

질문이 "MVC" 가 아니라 "MVC와 같은 **디자인 패턴**" 가 중점이었죠. 저는 디자인 패턴에 초점을 두고 싶었어요.

제가 느낀 장점은 **기능 분리와 의존성으로부터 자유로워지기**에요. 어플리케이션의 두 종류의 핵심 로직인 **도메인 로직**과 **뷰 로직**은 제대로 분리해내면 얻어낼 수 있는 이점이 크다고 생각해요.

두 핵심 로직을 분리하고, 직접적인 소통을 지양한다는 것은 다르게 말하면 서로의 의존성이 적다는 것을 의미하고, 갑자기 특정 뷰나 도메인 로직은 없애거나 다른 것으로 교체해도 영향을 미치는 경우가 적으니 유지보수에 적합한 형태가 된다고 생각해요. 기능들이 복잡하게 얽혀있어 꼬인 실처럼 기능이 서로 크게 의존한다면, 하나의 간단한 기능을 바꾸려해도 굉장히 많은 부분의 코드에 영향을 줄 것이고, 이는 의도치 못하게 프로그램이 작동될 수 있음을 이야기할 수 있어 보여요.

다른 디자인 패턴들을 사용하더라도 이들이 지향하는 분리가 있을 것이라고 생각해요.

> 2. MVC 패턴을 사용하시면서, 혹시 "불편하셨던 점이나, 이런 점은 단점으로 다가왔다" 라는 게 있으셨다면, 공유해 주실 수 있나요?

저는 로직이 많아지면 많아질수록 Controller가 비대해지는 것이 불편한 점으로 다가왔어요. 모델과 뷰는 필요한 경우 복잡한 로직을 언제든지 나눠 모듈화할 수 있어요. 그래서 작은 여러 개의 Model과 View로 나누는 것이 용이했었죠. 앞서 설명해 드렸지만, 의존성이 적은 위치에 있거든요.

Controller는 그렇게 하기가 힘들었었어요. Controller는 일종의 진행자에 가까운 역할을 담당하기 때문에, Controller을 나누는 점에서 어려움을 느꼈던 것 같아요. 저는 이를 일종의 MVC 패턴의 한계라고 생각하고 있어요.

아래에 제가 작년에 관련 사항에 대해 코드리뷰를 받은 링크를 남겨 보아요. 그냥 이런 고민을 했구나... 정도만 이해하셔도 될 것 같아요. 구조는 제가 PR을 쓸 때 그림으로 그려놓았기 때문에 Controller에 꽤 부담이 가는 구조라는 게 보이실 겁니다.

- https://github.com/woowacourse/javascript-lunch/pull/66

이로써 질문에 모두 답변드렸고, 제 생각도 공유해 드렸어요. JavaScript에 생소하셨을 텐데 2주 동안 따라오시느라 정말 고생 많으셨어요.

3주차부터는 이제 순수 JavaScript를 사용하는 것을 떠나 React라는 라이브러리를 이용해 본격적인 웹 개발에 들어가실 거에요. 라이브러리를 이용하지만, React가 JavaScript를 기반으로 두는 라이브러리이므로, JavaScript 개념들은 여전히 많이 나오고, 여기에 더해 React만의 개념들도 상당히 많이 나올 거에요.

많이 생소하고 어려우실 수도 있겠지만 화이팅입니다. 드리고 싶은 조언은, 각 기술의 사용 이유와 원리를 알아가는 것은 물론 중요하지만, 먼저 해봐도 좋은 점은 가이드를 따라가면서 사용법을 익히고, 그 과정에서 새로움과 재미를 느끼는 것이라고 생각해요.

기술의 원리와 사용 이유는 어느 정도 익숙된 이후 해도 늦지 않을 것이라고 생각해요.

그럼, 3주차도 화이팅입니다! 이만 놔드릴게요 👋🏻 ✔️

2024-10-04 16:56 UTC, wzrabbit commented on src/model/BaseballGame.js
> +            if (userNumbers[i] === this.computerNumbers[i])
직접 차이점을 인지하신 상태에서 사용해 주신 것이 맞군요. 잘하셨습니다. Airbnb 컨벤션에 `==`와 `!=` 사용을 금지하는 조항이 있기는 했지만 `===` 와 `==` 의 차이점을 인지하신 채로 사용하시는 것을 원했습니다.

## 1️⃣ `==` vs. `===`
엄밀히 다시 `==`와 `===`를 설명드리자면,
- `==`/`!=` 는 **동등 연산자**로, 두 값이 일치하는지를 비교하는데, 두 값의 자료형이 다르다면 **자동으로 형변환을 한 후** 값을 비교합니다.
- `===`/`!==` 는 **일치 연산자**로, 두 값이 일치하는지, 그리고 두 값의 타입이 일치하는지를 모두 비교합니다.

## 2️⃣ `==` 가 많은 상황에서 추천되지 않는 이유
`==`는 단순히 조금 느슨한 비교 연산자로써 사용되는 정도로 보이나, 실제로는 꽤나 사용하는 것이 지양됩니다. 왜 그런지 이제 설명해 보겠습니다.

![image](https://github.com/user-attachments/assets/ac67d4fb-9847-43dd-8c26-c2c4b81276c7)

- JavaScript는 약타입 언어이고, 암묵적인 형변환이 (너무) 유연하게 잘 일어나는 언어입니다. 이로 인해 아래와 같이 납득이 힘든 상황에서도 `==` 를 사용하는 경우에는 `true`를 반환하는 것을 보실 수 있습니다.
- 이렇게 JavaScript가 묵시적으로 해 주는 형변환은 편리해 보이지만, 실제로는 예상치 못한 상황에서 일어나는 경우가 많으며, 많은 경우 개발자의 실수로 이 상황이 발생합니다. 그런데 이 상황에서 동등 연산자를 사용하는 경우 통과하면 안 되는 조건 등이 통과해 버그를 찾지 못할 수 있습니다. 요약하면 이 특성이 **개발자의 의도에 벗어나는 상황을 캐치하기 어렵게 만들고, 디버깅을 어렵게 만들 수 있음**을 의미합니다.
- 타입에도 개발자의 의도가 담겨 있습니다. 문자열을 사용하도록 개발자가 구현해 둔 함수에 다른 개발자가 정수를 넣는다면, 개발자에 의도에 반하게 되며 올바르게 작동하지 못할 수 있을 것입니다. `===` 를 이용해 타입까지의 일치를 확인하는 것은 개발자의 의도에 따르는지를 더 엄격하게 검사하기도 하는 것입니다.

아이러니하게도 JavaScript는 타입이 굉장히 유연하면서도 타입을 매우 소중히 다뤄줘야 하는 언어기도 합니다.

## 🍿 그냥 여담
여담으로 저는 ESLint라는 도구를 이용해 `==` 를 사용하는 경우 아예 에러가 발생하도록 설정해 두고 사용하고 있습니다. 사실 기본값이기도 해요. ESLint는 나중에 사용하시겠지만, 지금은 커스터마이징이 용이한 높은 코드 품질을 위한 코드 스타일 검사 도구 정도라고 생각해 주셔도 됩니다.
![image](https://github.com/user-attachments/assets/40ac87c4-ff37-44a2-932e-f7bfa6993afd)

2024-10-04 16:56 UTC, wzrabbit commented on src/controller/BaseballGameController.js
> +    }
제가 실수로 코드를 잘못 읽은 채로 코멘트를 달았었어요. 죄송합니다 😓 다시 제대로 설명해 보겠습니다.

1. `this.BaseballGameView.toggleButtons(false)` 의 경우 View 로직을 Controller가 담당하는 것이 아니라, Controller가 View한테 자신의 일을 하도록 지시하는 것에 가깝다고 생각합니다. 따라서 MVC 원칙을 깬 것이 아니라고 생각하며, 제가 이 코드를 잘못 봤었습니다.
2. `alert`의 경우에는 `setTimeout`과 함께 사용되어 특수한 로직을 수행하고 있으니 View로 옮겨져도 괜찮다는 생각이 들며, 이미 잘 반영해 주신 것을 확인했습니다.
3. 아니요, 저는 이상하지 않다고 생각합니다. Controller의 역할 특성상 유저의 입력에 대해 처리를 해 줄 수 있어야 하고, 이에 따라 **View의 상황을 알아야 하는** 위치에 있기도 합니다. 따라서 리스너를 Controller에 두는 것은 전혀 이상하지 않다고 생각합니다. 잘 하셨어요!

2024-10-04 17:00 UTC, merged