[1주차] 숫자 야구 게임 미션 제출합니다
Greedy-FrontEnd-Study/javascript-baseball-precourse pull request #4
Opened 2024-09-24 06:48 UTC by ye6194

요즘 리액트만 쓰다보니 js로만 코딩하려고 하니까 헷갈려서 시간이 좀 걸렸던 것 같아요. 😂
분명히 예전에 공부한 내용인데도 기억이 안나서 다시 찾아봤네요

공통 요구사항 중에 들여쓰기를 2까지만 허용한다는 문항이 있는데 최대한 지키려고 노력하다가 countSkrikeBall() 함수에서 딱 한번 지키지 못했습니다ㅠㅠ
제가 한 방식 이외에 다른 좋은 방식이 있다면 공유 부탁드려요!

그리고 웹에서 테스트하면 잘 되는데 터미널에서 npm run test를 하면 테스트에 통과하지 못하는 문제가 있어요.
테스트 코드를 보면 정답이 425, userinput이 456일 때 "1볼 1스트라이크"가 표시되어야 하는데 제 코드는 "낫싱"이라고 뜬다고 해요.
하지만 웹에서는 "1볼 1스트라이크"라고 정상적으로 떠요. 뭐가 문제인지 잘 모르겠어요🤔

<br/>
이 밑은 제가 예전에 공부했었는데 까먹었다가 다시 찾아본 것들, 새롭게 알게된 것들을 정리한 글입니다!
<details>
<summary></summary>
<div markdown="1">

- onClick과 addEventListener의 차이
onClick은 한 요소에 하나의 콜백만 달 수 있고, addEventListener는 한 요소에 여러 번 달 수 있습니다.
[출처] https://velog.io/@steadygo247/TILonclick%EA%B3%BC-addEventListener-%EC%B0%A8%EC%9D%B4
<br/>

- 새로고침 location.reload()
현재 페이지 리로드
[출처] https://developer.mozilla.org/ko/docs/Web/API/Location/reload
<br/>

- NaN: 숫자 유형의 값이지만 숫자가 아닌 특수한 값
Number()은 항상 number 타입의 값을 반환합니다. 숫자로 변환할 수 없는 값은 NaN(Not a Number)을 반환하더라도, 타입은 항상 number 타입입니다. 따라서 typeof NaN를 하면 "number"라고 출력됩니다. 즉, NaN은 숫자 유형의 값이지만, 숫자가 아닌 특수한 값입니다.
<br/>

- Number()와 parseInt()
https://velog.io/@blackwidow/parseInt%EC%99%80-Number%EC%9D%98-%EC%B0%A8%EC%9D%B4
<br/>

- 구조 분해 할당
여러 값을 반환할 때, 그 값들을 받을 때 배열 구조 분해 할당을 써야합니다.

```
// ❌
return strikeCnt, ballCnt;
const strikeCnt, ballCnt = countStrikeBall(computerString, userString);

// ⭕
return [strikeCnt, ballCnt];
const [strikeCnt, ballCnt] = countStrikeBall(computerString, userString);
```

</div>
</details>

2024-09-25 12:11 UTC, bae-kh commented
좋은 코드 잘 봤습니다!!

코드를 봤을 때 너무 깔끔하게 짜셔서 이렇게 짤 수도 있구나라고 놀랐습니다.

ball count를 세는 부분에서 if 문 하나로 깔끔하게 짠 코드와 
validate.js 를 따로 만들어 computerinput을 100, 999 사이 수로 생성하고 validate 로 검사하는 코드 부분이 인상적 이였습니다. 

그나마 제가 할만한 피드백은 validate.js에서  중복된 수가 있는지 확인하는 함수에서 if 문을 길게 쓰는 것이 아니라 Set을 사용하면 좀 더 가독성이 좋은 코드가 될 것 같아요.

2024-09-26 11:18 UTC, ye6194 commented
> 좋은 코드 잘 봤습니다!!
> 
> 코드를 봤을 때 너무 깔끔하게 짜셔서 이렇게 짤 수도 있구나라고 놀랐습니다.
> 
> ball count를 세는 부분에서 if 문 하나로 깔끔하게 짠 코드와 validate.js 를 따로 만들어 computerinput을 100, 999 사이 수로 생성하고 validate 로 검사하는 코드 부분이 인상적 이였습니다.
> 
> 그나마 제가 할만한 피드백은 validate.js에서 중복된 수가 있는지 확인하는 함수에서 if 문을 길게 쓰는 것이 아니라 Set을 사용하면 좀 더 가독성이 좋은 코드가 될 것 같아요.


Set()으로 중복 제거하는 방식은 생각하지 못했는데 그렇게 고치니까 원래 코드보다 깔끔해졌어요!!
좋은 의견 감사합니다👍

2024-09-26 15:44 UTC, Indigochi1d commented
@ye6194 
안녕하세요 예은님! 저는 금요일마다 찾아오는 그리디 메인테이너 김범수입니다. 생애 첫 리뷰라 조금 떨리기도 하네요! React로 하시다가 VanilaJS를 사용하는 미션으로 돌아오니 어떠셨는지 너무 궁금해요. 지금 시각이 금요일 새벽인데 조금 이따가 물어볼 생각에 조금 신나(?)기도 합니다😅

아쉽게도 테스트는....😭 코드를 아직 제대로 읽진 않았지만 지금부터 읽어보며 왜 안되는지 저도 생각해보겠습니다! 

그럼 리뷰 시작해보도록 할게요!

2024-09-26 16:46 UTC, ye6194 commented
기대하고 있겠습니다!!😮

2024-09-26 17:21 UTC, Indigochi1d requested changes
코드리뷰를 마쳤습니다🤔 전체적으로 잘 작성하신 것 같은데 테스트가 통과하지 못해 아쉽네요 ㅠㅠ
다음주 미션때 MVC패턴으로 이 코드를 바꾸게 될텐데 그 때 수정하시면서 어떤게 문제였는지 찾아보면 좋을 것 같아요! 아마 이벤트핸들러 문제 같은데 저도 더 자세히 뜯어보며 공부해보겠습니다! 
이번주 미션 수고 많으셨고 이따 봐요~

2024-09-26 17:37 UTC, ye6194 commented on .gitignore
> +review.md
이번 미션을 진행하면서 새로 알게된 것들, 공부했었는데 기억이 안나서 다시 찾아본 것들 등을 정리해놓은 파일입니다. 여기서 일부는 pr을 작성하면서 토글에 적어놓았어요! 뭔가 깃허브에 올리기에는 부끄러워서ㅎㅎ.. gitignore에 적어놓았습니다

2024-09-26 17:42 UTC, ye6194 commented on docs/README.md
> +   사용자가 정답을 맞추면 게임이 종료되고 재시작 버튼이 노출되게 함. 재시작 버튼을 누르면 게임이 다시 시작됨
저도 작성하면서 뭔가 더 구체적으로 적어야 할 것 같은데 뭘 더 적어야 할지 모르겠더라고요. 범수님이 조언해주신 부분 참고해서 수정하고 다음 미션에서는 기능 요구 사항을 더 구체적으로 적어보겠습니다!!

2024-09-26 17:45 UTC, ye6194 commented on src/index.js
> +submitBtn.addEventListener("click", BaseballGame);
getElementById를 사용한 특별한 이유는 없고 그냥 단순히 돔 트리에서 한 요소만 가져오는게 목적이어서 그랬습니다! 여러 요소를 가져와야한다거나 하면 getElementsByClassName이나 querySelectorAll을 사용했을 것 같습니다.

2024-09-26 17:47 UTC, ye6194 commented on src/index.js
> +  }
include() 함수는 처음 보는데 제 긴 코드를 짧게 줄일 수 있네요😮 더 찾아보고 공부해서 수정하겠습니다!!

2024-09-26 17:48 UTC, ye6194 commented on src/index.js
> +    // const computerString = String(425);
넵 알겠습니다

2024-09-26 17:52 UTC, ye6194 commented on src/index.js
> +  };
오 그렇네요! 이렇게 수정하겠습니다

2024-09-26 18:10 UTC, ye6194 commented on src/index.js
> +    getUserInput(event);
1. <input>태그의 값을 userInput으로 받습니다.
<br/>

2. userInput의 유효성 검사를 합니다.
2-1. (if (!validateInput(userInput))~ 부분) validateInput 함수에서 userInput에 중복된 숫자가 있는지 검사합니다. 
중복된 숫자가 있다면 alert를 띄우고 입력창(<input>)을 비웁니다. 여기서 반환된 ""은
```
userInput = getUserInput(event);
  if (userInput === "") return; // 잘못된 입력이 들어왔을 때는 경고창만 띄우고 아무것도 하지 않음
```
이 부분에서 사용됩니다.
<br/>

  2-2.  (userInput = validateUserInput(userInput)~ 부분) userInput이 숫자가 아닌 경우, 첫번째 숫자가 0인 경우, 길이가 3이 아닌 경우 validateUserInput 함수에서 ""을 반환합니다. 여기서 반환된 ""도 위에 적은 부분에서 사용됩니다.
<br/>

3. (맨 마지막 return userInput 부분) 올바른 userInput을 반환합니다.
 
지금 글로 적어보니 쓸데없이 코드를 복잡하게 짠 것 같네요😂 더 좋은 방법이 있을 것 같아요...

2024-09-26 18:12 UTC, ye6194 commented on src/validate.js
> +  return new Set(input).size === input.length;
강현님이 추천해주신 방법입니다!! 저도 예전 제 코드보다 이 코드가 더 좋은 것 같아요.

2024-09-26 18:13 UTC, ye6194 commented on src/validate.js
> +}
헉 생각하지 못했던 경우네요...!! 매번 ㅇㅇㅇ, asdf, 01, 999 같은 입력만 검사해보고 그렇게는 해보지 않았었어요. 수정하도록 하겠습니다!

2024-09-26 18:20 UTC, ye6194 commented on src/index.js
> +function BaseballGame() {
BaseballGame() 말씀하신 거 맞나요?? 아예 이 함수를 export 할 생각도 못했어요😮 여기서 export를 쓰는게 더 좋나요?? 그렇다면 왜 그런지 이유가 궁금합니다!!

2024-09-26 18:29 UTC, Indigochi1d commented on src/index.js
> +let userInput = "";
이 내용은 2주차 미션하실때 리팩토링하시면서 구현하시면 좋을 거 같아요!

2024-09-26 18:38 UTC, Indigochi1d commented on src/index.js
> +function BaseballGame() {
"모듈"에 대해서 저도 다시 한번 공부할 수 있는 포인트였네요!
index.js가 index.html에서 모듈로 불러와지는 경우, 그 파일 내의 코드가 다른 모듈과 연결될 필요가 없으면 export를 생략해도 된다고 해요. 결론은 export 를 사용하지 않아도 되는데 저 같은 경우는 모듈이라고 생각되는 것은 export를 반드시 붙이는 버릇이 있어서 리뷰를 적었던 것 같습니다!

2024-09-28 13:31 UTC, merged