[1주차] 숫자 야구 게임 기능 구현 미션 제출입니다.
Greedy-FrontEnd-Study/javascript-baseball-precourse pull request #5
Opened 2024-09-24 09:16 UTC by bae-kh

자바스크립트를 이번 기회에 처음 다루게 되어서 시간이 많이 걸렸습니다..
모르는 내용도 아직 많고 시간도 부족해서 코드가 많이 부족합니다.
적극적인 피드백 해주시면 감사하겠습니다.!

공통 요구 사항을 지키려다 보니 코드가 더러워지기도 하였고 못 지킨 부분도 많습니다..
아직 웹테스트는 통과하지 못했고 오류가 나는데 최대한 마감 기한 지키기 위해서 지금 제출하게 되었네요.
 피드백 해주시면 마저 코딩하면서 적극 수용하겠습니닷 
많이 부족하겠지만 잘부탁드립니다!

2024-09-25 07:22 UTC, ye6194 commented
잘 봤습니다!!

다음 사항을 지켜주시면 더 좋은 코드가 될 것 같아요.
1. 모듈 분리
- 하나의 파일에 모두 넣기 보다는 관련있는 함수끼리 묶어서 다른 파일에 저장하고 export 한 뒤, index.js에서 import해서 받아오기
<br/>

2. 들여쓰기 depth 줄이기
- 현재 들여쓰기가 최대 5까지 되어있는데 2까지 줄이도록 노력하기 (모듈을 분리하는 것도 들여쓰기 줄이기에 도움될 것 같아요)
<br/>

3. 자바스크립트 스타일 가이드
- 함수 이름에 언더바 빼기
- 단항 연산자 사용하지 않기 (ball++ 보다는 ball += 1)
<br/>

그리고 추가로
1. 커밋 단위 (기능 목록에 적은대로)
2. 커밋 메시지 적을 때 컨벤션 지키기

이렇게 하면 더 좋을 것 같습니다!!

2024-09-26 17:30 UTC, Indigochi1d commented
@bae-kh 
안녕하세요 강현님! 그리디 메인테이너 김범수입니다! 지금은 새벽...2시 24분인데요! JS를 처음 접하셨는데 어떠셨는지 어렵진 않으셨는지 궁금하네요..! 코드가 어떨지 굉장히 궁금한데요 부푼 마음을 안고 읽어보도록 하겠습니다!
![image](https://github.com/user-attachments/assets/727de9ae-ace2-4328-9f0c-8ce11878073e)
지금부터 **코드리뷰**를 시작해볼게요!

2024-09-26 18:42 UTC, Indigochi1d requested changes
강현님 리뷰를 마쳤습니다..헥헥..ㅋㅋㅋ
test가 안되는 원인이 무엇인지 저도 더 자세히 코드를 읽어봐야 할 것 같습니다! 
2주차 미션때 이런 점들을 보완해서 코드를 작성하시면 더 좋을 것 같아요! 수고하셨고 이따 뵙겠습니다!


커밋메시지를 컨벤션대로 작성해야해요!
[링크](https://velog.io/@shin6403/Git-git-%EC%BB%A4%EB%B0%8B-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)를 읽어보시고 2주차 미션때 적용해주세요!

2024-09-26 18:42 UTC, Indigochi1d commented on src/index.js
> +    }
if-else if-else문이 가독성이 떨어지고 있는 것 같습니다..! 볼과 스트라이크를 play메서드에서 다 체킹하며 해결하고 있어서 그런데요..! 이 부분을 볼과 스트라이크를 체킹하는 메서드를 구현하시고 체킹된 값으로 스트라이크 or 볼을 return 하시면 더 간단하고 읽기 쉬운 코드가 될 수 있을거에요!

2024-09-26 18:42 UTC, Indigochi1d commented on src/index.js
> +      document.querySelector("#result").innerHTML = `<div style="font-size: 20px;"><b>🎉정답을 맞추셨습니다🎉</b></div><br>게임을 새로 시작하시겠습니까?`;
innerHTML을 사용하셨는데 XSS공격을 대비하려면 어떻게 코드를 바꿀 수 있을지 생각해보시면 좋을 것 같아요!

2024-09-26 18:42 UTC, Indigochi1d commented on src/index.js
> +      document.getElementById('game-restart-button').style.display ='block';
display를 block과 none으로 표현하셨군요! 저는 visible 속성을 사용해서 했는데 이런 방법도 있네요!

2024-09-26 18:42 UTC, Indigochi1d commented on src/index.js
> +    document.querySelector('#submit').addEventListener('click', (event) => {
`getElementById`와 `querySelector`를 같이 사용하셨네요! 왜 그렇게 하셨는지 이유를 여쭤봐도 될까요?

2024-09-26 18:42 UTC, Indigochi1d commented on src/index.js
> +let baseballGame = new BaseballGame();
baseballGame가 사용되지 않고 있어요! 실행을 의도하신거라면
```
new BaseballGame() 
```
만 적어주시는게 맞습니다!

2024-09-26 18:42 UTC, Indigochi1d commented on src/validate.js
> +  let setinput = new Set(input);
Set을 활용해서 input의 중복제거를 한 점 잘하셨습니다!

2024-09-26 18:42 UTC, Indigochi1d commented on src/validate.js
> +  if (isNaN(Number(input)) || input.includes("0")|| setinput.size !=3) {
이 if문은 코드가 가독성이 매우 좋네요! 잘 작성하셨어요!

2024-09-29 10:40 UTC, merged