[1주차] 숫자 야구 게임 기능 구현 미션 제출합니다
Greedy-FrontEnd-Study/javascript-baseball-precourse pull request #6
Opened 2024-09-24 12:24 UTC by Songhyejeong

안녕하세요! 

우선 이번 과제는 첫 과제인 만큼 구현 하면서 새롭게 알게된 것들이 정말 많았던 것 같습니다. 

1. 이번 과제를 통해서 class를 처음 써봤는데요! 가장 어려웠던 부분이었습니다. 메인 함수 이외의 다른 함수에도 적용하고 싶었는데 생각보다 이해하는데 시간이 오래걸려서 적용하지 못했습니다ㅠ

2. 코드 컨벤션도 처음 읽어봤는데 새롭게 알게 된 것이 정말 많았습니다! 코드 컨벤션을 보면서 몇가지 코드를 수정 했는데 아직 부족해보입니다.  

### 궁금한 점

- 모듈을 불러오면서 자바스크립트 확장자를 명시하지 않고 불러오는 방법을 모르겠습니다.
- 메인 함수에는 최대한 게임을 이해하기 쉽게 짜보려했는데 나머지 함수들의 역할을 제대로 나눴는지 궁금합니다. ( + 간단한 기능 구현은 굳이 함수를 모듈로 나누지 않아도 괜찮은지)
혹시 알고 계시면 알려주시면 감사하겠습니다..!

이외에도 개선사항 필요한부분 피드백 부탁드립니다!
감사합니다! 잘부탁드립니다 :)

2024-09-25 13:00 UTC, gogo1414 reviewed
안녕하세요, 혜정님!
리뷰어 김준수입니다😊

작성해주신 코드 너무 잘봤어요! 배울 점을 많이 느꼈답니다.
기능에 맞게 파일(?), 객체(?) 뭐라고 불러야할 지 모르겠지만 분리를 잘 하신 점이 되게 인상 깊었어요👍
저는 index.js에 다 때려넣어서 보기가 너무 불편한데 혜정님 코드는 보기 편해서 아주 좋았답니다!!

우선 궁금한 점 2가지를 적어주셨잖아요??
저도 글을 읽고 궁금해져서 첫번째 질문이신 모듈을 불러올 때 자바스크립트 확장자를 명시하지 않고 불러오는 방법에 대해서 찾아봤어요!
1. CommonJS 모듈 사용 - require 함수를 사용하면 파일 확장자를 생략할 수 있다고 하네요.
2. 번들러 사용 - Webpack이나 Rollup 같은 모듈 번들러를 사용하면 확장자 없이도 모듈을 import 할 수 있다고 합니다!

그외에도 TypeScript 또는 Babel 사용 Node.js 설정 변경 등등이 있다고 하네요!
(제가 직접 해본 것들이 아니라 찾아본거라 장담은 못합니다..🥲)

두번째 질문에 대한 답은 나눌 수 있는 부분이고 나눴을 때 이점이 있다고 느껴지신다면 그렇게 하시면 좋을거 같아요. 저도 그런 부분에 대해서 의문점이 생길때면 서비스 방향이 다르게 바꼈을 때 변경과 확장 등에 유리한 지 판단해보고 결정을 내렸던 것 같네요!

미션 하시느라 고생 많으셨습니다!!

2024-09-25 15:12 UTC, Songhyejeong commented on src/createResultMessage.js
> +  const strikeMessage = strikeCount !== 0 && `${strikeCount}스트라이크`;
> 해당 코드에서 약간 궁금한게 있어요..! 뒤에 !== 0 && ~ 로 이어지는게 ? A : B 와 같은 원리인가요??

```
if(ballCount!==0){
//..
}
```
와 같은 원리 입니다! 참고로 코드 컨벤션 확인해보니 제 코드 보다 if문 쓰는게 좋다고 하네요!



> 아래 if, else if, else 에서 사용하실 때 () 안에 ballMessage, strikeMessage 가 있는게 어떤 영향이 있는건지도 궁금해요!

위의 코드에서 ballCount가 0이 아닐때 문자열을 할당 하는데, ballCount가 0이면 ballMessage는 false 예요 그래서 두 개 다 true 일 때, 즉 ball과 strike가 0이 아닐때 두 개의 문자열을 합치는 코드를 짜봤어요!

2024-09-25 15:14 UTC, Songhyejeong commented on src/index.js
> +const restartButton = document.querySelector('#game-restart-button');
저도 이 두가지 차이 점에 대해서 궁금해서 찾아봤었는데 getElementById가 querySelector 보다 성능이 좋다는? 글을 봤었어요
restartButton에만 querySelector를 사용한이유는 restartButton만 css 속성을 변경해서였어요!
id 값만 참조할 때는 getElementById를, 이외의 것들은 querySelector를 사용하라는 글을 봐서 저렇게 해봤는데
정확한 차이점과, 어떤걸 사용해야 좋은 코드인지는 확신이 안드네요..

2024-09-25 15:14 UTC, Songhyejeong commented on src/compareAnswer.js
> +      }
저도 준수님 코드 보고 `includes()` 이용하는게 훨씬 간결할 거라는 생각을 했어요!

2024-09-26 03:54 UTC, Songhyejeong commented
리뷰 감사합니다 👍  
의견 남겨주신거 반영해서 코드 수정했습니다!
궁금한 점도 자세하게 답변해주셔서 감사합니다 :) 공부해서 적용해보려했는데 계속 코드가 실행이 안돼서.. 이부분은 조금 더 공부해서 적용해보겠습니다!

2024-09-26 07:36 UTC, gogo1414 commented on src/compareAnswer.js
> +      }
그렇게 생각하셨으면 다행이네요!

2024-09-26 07:37 UTC, gogo1414 commented on src/createResultMessage.js
> +  const strikeMessage = strikeCount !== 0 && `${strikeCount}스트라이크`;
아 숫자로 boolean을 반환을 고려하신거네요!

이해했습니다 설명해주셔서 감사해요😄

2024-09-26 07:38 UTC, gogo1414 commented on src/index.js
> +const restartButton = document.querySelector('#game-restart-button');
저도 한번 찾아서 혜정님이 해주신 코드리뷰에 답변했답니다! 한번 참고해보시면 좋을거 같아요!

2024-09-26 14:29 UTC, wzrabbit requested changes
@Songhyejeong 👋🏻 

안녕하세요, 혜정님! 저는 그리디의 외부 리뷰어를 맡은 김의천이라고 합니다. 만나뵙게 되어 반가워요 😊
그리디에서의 첫 번째 미션은 어떠셨나요? React를 하시다가 순수 JavaScript를 사용하는 미션으로 돌아가니 태초마을로 오신 듯한 느낌이 들지는 않으셨나 궁금하네요

코드 확인해보았고 전체적으로 함수가 기능별로 잘 구분되어 있는 것이 눈에 띄었네요, 특히 `index` 파일 하나로 모든 로직을 처리하시기보다는 관심사에 따라 여러 모듈로 나누시는 등 모듈의 장점을 상당히 잘 살리셨다고 생각합니다. 테스트도 실행해 보았는데 역시 잘 통과하고요 🥳 

상호 리뷰에서는 첫 번째 질문에 대한 답변이 나왔으니 저는 두 번째 질문에 대한 답변 간략하게 적고 넘어가 보겠습니다.

> 메인 함수에는 최대한 게임을 이해하기 쉽게 짜보려했는데 나머지 함수들의 역할을 제대로 나눴는지 궁금합니다. ( + 간단한 기능 구현은 굳이 함수를 모듈로 나누지 않아도 괜찮은지)
혹시 알고 계시면 알려주시면 감사하겠습니다..!

네, 깔끔하게 잘 나누신 것 같습니다. 이렇게 부수적인 기능들은 모듈로 나눠두면 메인 로직에서는 게임 진행에 필요한 구현만 신경써도 되고, 각 함수/클래스의 덩치가 작아지므로 코드를 읽는 데 있어서 더 이해하기 편할 것이라고 생각합니다.

만약 아주 작은 기능을 하는 함수들조차 각각을 모두 모듈로 나눠서 모듈의 개수가 지나치게 많아지는 것을 걱정하신다면 — **비슷한 관심사를 가지는 함수들**, **하나의 메인 기능을 위해 보조적인 역할을 하는 함수들**과 같이 관련도가 높은 함수들을 하나의 모듈을 묶어 관리하는 방법도 있을 것 같습니다.

비유하자면 **도구**를 함수로 본다면 모듈은 **공구 상자** 정도로 볼 수 있지 않을까요? 저는 이렇게 생각하지만 개발자분들마다 생각은 다양할 것 같습니다.

작성하신 코드에 대해 제가 개선, 그리고 혜정님의 성장을 위해 드리고 싶은 조언은 **예측하기 쉬운 코드를 만들고, 이를 통해 코드를 읽기 쉽도록 만들어보자**입니다. 코드를 읽기 쉬우면 협업이 원활해지고, 유지보수하기 좋은 코드가 될 거에요.

- 변수명, 함수명을 정할 때는 역할을 유추하기 쉽고 명확한 이름을 짓자, 이름이 길어지는 것을 두려워하지 말자
- 함수명 역시 리턴하는 값이 무엇일 지 예측하기 쉽도록 함수명과 매개변수명을 잘 다듬어보자
- 변수의 재할당에 주의하여 불변성을 보장하고 예측하기 쉬운 코드를 만들어 나가보자

이를 바탕으로 혜정님만의 코드를 다듬어보시기 바랍니다, 화이팅이에요! 👍🏻

2024-09-26 14:29 UTC, wzrabbit commented on src/index.js
> +      this.process();
`BaseballGame.process`의 경우 의미가 포괄적이어서, 함수명만으로는 무슨 역할을 하는 함수인지 예측하기 어려울 것 같다는 생각이 드는데, 어떻게 생각하시나요? 함수 이름의 의미가 보다 구체적으로 바뀐다면 더 알아보기 쉬운 코드가 될 수 있을 것 같습니다!

제가 함수 내부의 내용을 읽었을 때 `Baseball.process`는 숫자야구를 한 라운드 돌리는 함수처럼 보여요. 입력값을 받는 함수를 호출하고 있고, 이를 기반으로 결과를 도출한다음, 결과를 웹페이지에 보여주는 함수를 호출하는, 나름 중심이 되는 함수네요?

제가 만약 이름을 지어본다면 `Baseball.playSingleRound`와 같은 이름을 떠올려볼 것 같아요, 의미가 잘 드러나는 함수명이면 무엇이든 좋으므로, 적합하다고 생각되는 이름을 지어주시면 될 것 같습니다!

2024-09-26 14:59 UTC, wzrabbit commented
> 공부해서 적용해보려했는데 계속 코드가 실행이 안돼서.. 이부분은 조금 더 공부해서 적용해보겠습니다!

혹시 막히시는 부분이 있다면 리뷰 반영 시 같이 말씀해 주시거나, Discord의 `#개발-질문` 에 코드 올려주세요~ 해결책을 같이 찾아보면 좋을 것 같습니다

2024-09-27 04:25 UTC, Songhyejeong commented on src/index.js
> +      this.process();
querySelector에 대해서 덕분에 자세히 배워갑니다! 너무 정성스러운 답변 감사해요 :) 
둘의 차이에 대해서 명확하게 알지 못했는데 너무 깔끔하게 설명해주셔서 이해가 잘되어요..! 
의천님 의견대로 저도 querySelector 사용을 지향하도록 하겠습니다!


> `BaseballGame.process`의 경우 의미가 포괄적이어서, 함수명만으로는 무슨 역할을 하는 함수인지 예측하기 어려울 것 같다는 생각이 드는데, 어떻게 생각하시나요? 함수 이름의 의미가 보다 구체적으로 바뀐다면 더 알아보기 쉬운 코드가 될 수 있을 것 같습니다!
> 
> 제가 함수 내부의 내용을 읽었을 때 `Baseball.process`는 숫자야구를 한 라운드 돌리는 함수처럼 보여요. 입력값을 받는 함수를 호출하고 있고, 이를 기반으로 결과를 도출한다음, 결과를 웹페이지에 보여주는 함수를 호출하는, 나름 중심이 되는 함수네요?
> 
> 제가 만약 이름을 지어본다면 `BaseballGame.playSingleRound`와 같은 이름을 떠올려볼 것 같아요, 의미가 잘 드러나는 함수명이면 무엇이든 좋으므로, 적합하다고 생각되는 이름을 지어주시면 될 것 같습니다!

함수명에 대해서 깊이 고민해보지 못한 것 같네요 의천님이 말씀해주신대로 이름을 길게 쓰는 것을 두려워하지 말아야 할 것 같습니다!

2024-09-27 04:26 UTC, Songhyejeong commented on src/getUserInput.js
> +    inputValue = null;
저 경우들은 생각 못했었는데 조건을 더 빡세게 강화해야겠네요! 감사합니다!

2024-09-27 04:26 UTC, Songhyejeong commented on src/index.js
> +    resultText.innerHTML = null;
XSS 공격에 취약하다는 사실까지는 고려하지 못했는데 
찾아보니 textContent 혹은 innerText를 사용하는 편이 좋을 거 같아요!

2024-09-27 04:34 UTC, Songhyejeong commented on src/getUserInput.js
> +}
1. 얼리 리턴
얼리 리턴에 대해서 들어는 봤지만 어떤 점에서 좋은 코드 인지까지 생각하지 못했어요,, 의천님 덕분에 얼리 리턴을 어떤 경우에 사용해야하고, 어떤 이점이 있는지 배워갑니다!! 코드 짜면서 필요한 경우에 맞게 적용해보는 습관을 들여야겠네요! 정말 감사합니다 👍 
2. 매개 변수
저는 재할당 하는 것이 좋지 않다는 것은 알고 있었지만 그 이유에 대해서는 정확하게 알지 못하고 있었던 것 같습니다. 
가끔 값이 예상치 못한 값으로 변경하는 경우가 있었는데 그 이유도 덕분에 알아갑니다!
let을 사용하는 것을 지양하는 이유도 재할당이었는지 처음알게 되었구요! 의천님이 말씀해주신 얼리 리턴 사용해서 코드 수정해보겠습니다! 감사합니다!!

2024-09-27 04:35 UTC, Songhyejeong commented on src/createResultMessage.js
> +  const strikeMessage = strikeCount !== 0 ? `${strikeCount}스트라이크` : false;
저도 제 코드가 읽기에 조금 어려워 보인다고 생각했는데 이유를 알 것 같습니다! boolean 대신 비어있는 값의 의미를 전달해주는 값들을 사용하면 가독성이 훨씬 좋아지겠네요! 
다른 의도는 없었고 사실 "", null 이런 값들 보다 false를 직관적으로 생각해낸 것 같습니다....

2024-09-27 04:50 UTC, Songhyejeong commented
@wzrabbit 의천님 리뷰 잘 읽었습니다! 

우선 너무 자세하고 정성스러운 리뷰 감사합니다! 👍 
이해하기 쉽게 설명해주셔서 정말 많은 것을 배울 수 있었던 거 같아요..!
그리고 많이 부족하다는 것을 다시 깨달았던 것 같아요! 
코드 리뷰를 처음 받아 보는데, 미처 생각하지 못했던 것들, 그동안 애매하게만 알고 있던 것들을 확실하게 정리할 수 있어서 유익했어요!
정말 감사합니다 :)

그동안 좋은 코드가 무엇인지에 대한 고민을 자주 했었는데 의천님이 말씀해주신 것들이 모두 그동안 제가 작성한 코드들의 단점이었던 것 같네요.
앞으로 코드를 짤 때 이해하기 쉬운 코드, 예측하고 읽기 쉬운 코드, 변수 재할당 지양을 통해 좋은 코드를 작성해보는 노력을 해야할 거 같습니다!

정성스럽게 리뷰 달아주신거 다시 한 번 정독하면서 코드 수정해나가겠습니다!

감사합니다! 앞으로 잘 부탁드려요~!!

2024-09-28 10:48 UTC, wzrabbit approved these changes
@Songhyejeong 👋🏻

리뷰 반영 확인했습니다, 전체적으로
- 작성하신 코드에 적절하게 얼리 리턴을 시도해 보신 점
- 자칫 의미가 부족할 수 있는 변수 및 함수의 의미가 명확해 보이도록 개선해 보신 점
- 로직에 따라 `some` 등의 의도가 잘 드러나는 고차 함수를 사용해 보신 점

이 인상깊었습니다.

다음 미션은 이제 작성하신 코드를 MVC 패턴을 준수하는 코드로 리팩터링하는 작업인가요? 이미 익숙하실 수도 있고 아니면 생소하실 수도 있겠네요.
한 번 디자인 패턴을 적용해 보시면서, 이러한 디자인 패턴을 왜 사용하는 것인가를 생각해 보시면 성장에 도움이 많이 될 수 있을 것 같습니다.

또한 이미 아시겠지만 다음 리뷰에서는 제가 아닌 메인테이너님이 리뷰를 맡아주실 겁니다. 서로 다른 개발자의 의견을 들어볼 수 있는 좋은 기회이니 새로운 느낌의 코멘트들을 느끼시길 바라겠습니다.

이번 미션은 여기까지~ 다음 미션도 화이팅이에요! 👋🏻 

<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

2024-09-28 10:48 UTC, wzrabbit commented on src/createResultMessage.js
> +  const strikeMessage = strikeCount !== 0 ? `${strikeCount}스트라이크` : null;
`null`을 선택해주셨군요, 이제 의도가 잘 드러나는 느낌이 듭니다 👍🏻 다른 스터디원들은 빈 메시지를 의미하는 코드를 작성할 때 어떻게 작성하실 지도 여쭤 보시면 좋을 것 같아요.

2024-09-28 10:48 UTC, wzrabbit commented on src/index.js
> +    resultText.innerHTML = null;
오, 좋은 것 같습니다. 사실 구현상의 이유로 `innerHTML`를 사용하는 선택지가 있었을 수도 있었긴 하지만, 현재 케이스의 경우에는 단순히 텍스트만 변경해주는 작업이기 때문에 `innerHTML`까지 꺼내지는 않아도 괜찮을 것 같아보여 코멘트 드렸었습니다.

2024-09-28 10:48 UTC, wzrabbit commented on src/index.js
> +      this.process();
> 의천님 의견대로 저도 querySelector 사용을 지향하도록 하겠습니다!

이건 취향차이니까 두 쪽 다 충분히 사용해보시고, 어느 쪽이 더 취향가시는 지에 따라 정하셔도 좋을 것 같네요, querySelector가 마음에 드시면 계속해서 사용해주셔도 좋습니다.

2024-09-28 10:48 UTC, wzrabbit commented on src/getUserInput.js
> +}
모든 코드를 한 번에 재할당을 하지 않는 코드로 바꾸는 것은 쉽지 않을 것이고, 특히 로직이 복잡한 경우에는 오히려 재할당을 사용하는 코드가 깔끔해 보이는 쪽도 생길 수 있을 거라고 생각해요.
점차적으로, 재할당 없이 개선할 수 있는 코드가 보이는 코드를 위주로 개선해보시면 좋을 것이라는 생각이 듭니다 👍🏻

2024-09-28 10:48 UTC, wzrabbit commented on src/createResultMessage.js
> +  return '낫싱';
네! 특정 케이스에 걸려 결과가 확정된 상황이라면, 바로 시원하게 리턴해주면 코드의 뒤쪽에서 의도치 않은 실수가 일어날 가능성도 줄어들 거에요.

여기에 더해, 이전 케이스에서 조건을 만족하는 경우 항상 리턴이 일어나므로, 다음 조건문에서는 이전 조건을 고려할 필요가 없게 되니, `else` 까지 삭제해 버릴 수도 있어 보입니다. `else`라는 것은 앞 조건이 만족하지 않는 경우 실행하는 로직인데 앞 조건에 해당하는 경우 무조건 리턴이 일어나니까요.

2024-09-28 10:48 UTC, wzrabbit commented on src/index.js
> +  gameSettingAndStart() {
이름의 의미를 구체적으로 개선해주려는 노력이 많이 보입니다. 앞으로도 의미를 명확하게 부여하는 시도를 많이 해 주시면 좋을 것 같아요 👍🏻

2024-09-28 10:48 UTC, wzrabbit commented on src/getUserInput.js
> +  ) {
`Array.prototype.some` 👍🏻 👍🏻

상당히 좋은 선택이라고 생각합니다. 잘못 사용하면 실수를 남발할 수 있고, 내부의 로직을 봐야 흐름을 이해할 수 있는 `for`문과 달리 `some`을 사용한다면 리뷰하는 개발자 입장에서는 `some` 이 네 글자만 보고 내부의 조건을 하나라도 만족하는지 검사하려는 의도를 즉시 알 수 있게 됩니다.

고차함수의 적절한 사용은 가독성, 안정성, 불변성을 향상시켜주기 좋은 선택이 될 수 있을 겁니다, 아래의 블로그 게시글도 참고해 보세요
- https://dev-ellachoi.tistory.com/104

2024-09-28 10:59 UTC, merged