[2주차] 숫자 야구 게임 MVC 패턴 적용 제출합니다.
Greedy-FrontEnd-Study/javascript-baseball-precourse pull request #9
Opened 2024-10-01 11:52 UTC by Songhyejeong

안녕하세요 리뷰어님! :)  
이번 리뷰도 잘부탁드립니다!

MVC 패턴을 처음 공부해 봤는데 의존성을 없애는게 어려운거 같아요... 
특히 view가 controller에 의존하면 안되는 요구사항을 지키기 어려웠던 것 같습니다,,

코드 실행이 어디서부터 되는지 간단하게 설명 드리자면, controller에서 먼저 click 이벤트를 감지하고 게임이 시작됩니다 그 다음부터는 함수들 쭉 따라 보시면 될거 같아요!

### 궁금한 점

createComputerNumbers 함수가 제일 처음 게임이 시작 될 때 한 번만 실행 시키고 싶어서 계속 수정시키다 보니까 점점 산으로 가더라구요,,

그래서 그냥 사용자 입력할 때마다 실행되게 하고 게임이 끝나면 computerNumbers를 초기화하는 함수를 만들었는데 사용자가 값을 입력할 때마다 이 함수가 실행되는게 마음에 조금 걸립니다
좋은 방법 알고계시다면 말씀해주세요!

+ 지금 Greedy 레포지토리로 머지할 수 없다고 뜨는데 괜찮을까요..?

감사합니다 👍

2024-10-02 16:13 UTC, ye6194 reviewed
안녕하세요 혜정님😊

코드 잘 봤습니다. 전체적으로 MVC 패턴을 잘 구현하신 것 같아요.
읽으면서 이렇게 할 수도 있구나 하는 생각을 많이 했어요!

또, bind(), some(), indexOf(), join() 등 제가 처음 보거나 사용 방법을 잘 몰랐던 메서드들이 많았었는데 덕분에 저도 알아갈 수 있어서 좋았어요.

2주차 미션 하시느라 수고 많으셨습니다. 3주차 미션도 같이 화이팅해요!🙌

2024-10-02 16:13 UTC, ye6194 commented on doc/mvc_class_diagram.png
자세하게 잘 작성하신 것 같아요😮

2024-10-03 04:50 UTC, Songhyejeong commented on src/utils/verifyUserNumbers.js
> +      numbers.some((input) => !Number.isInteger(parseInt(input))) ||
지난주차 리뷰에서 의천님께서 3.5, 1e2 와 같은 숫자가 입력 값으로 들어갔을 때도 생각해보면 좋겠다는 의견을 주셔서요!

input이 문자열이여서 숫자로 바꾼 후, 정수가 아닌 입력값이 있으면 true를 반환하는 코드 인데 
지금 보니 문자열을 정수로 바꾸는 parseInt가 아닌 숫자로 변환하는 Number()을 사용해야 했었네요,,

2024-10-03 04:51 UTC, Songhyejeong commented on src/model/BaseballGameModel.js
> +    if (ballCount !== 0 && strikeCount !== 0) {
그렇게 합치는 방법이 더 좋겠네요!!

2024-10-03 04:59 UTC, Songhyejeong commented on src/view/BaseballGameView.js
> +    this.restartButton.addEventListener('click', () => {
이벤트 리스너 등록 횟수에 대해서 처음 생각해보는데 예은님 말씀대로 한 번만 등록되어야할 거 같아요,..!
방법에 대해서는 잘 모르겠어서.. 찾아보고 수정하겠습니다 !!

2024-10-04 12:32 UTC, Indigochi1d commented
안녕하세요 혜정님!! 이번 리뷰는 스터디가 끝나고 하게 되어서 몰입감이 약간 떨어질 수 있지만 그래도 열심히 코드를 읽어보며 리뷰를 시작해보도록 하겠습니다!

2024-10-04 15:04 UTC, Indigochi1d requested changes
2주차 리뷰를 끝냈습니다! 
혜정님의 경험 중 이렇게 디자인 패턴+VanilaJS 으로 제품을 만들어낸 경험이 있으셨을지 아닌지 모르겠지만 디자인 패턴을 사용해보면서 왜 이 패턴을 사용하는가? 어떤 trade-off 가 있는가? 에 대한  질문을 스스로 해보면서 성장하는 계기가 되었을 것 같아요.

전체적으로 코드는 깔끔하다고 느껴졌어요. 그래서 읽기 매우 쉬웠습니다ㅎㅎ(감사해요). 또 model-view-controller를 잘 나누신 것 같고 특히 controller를 만드실 때 캡슐화가 잘 이루어진 것 같아서 저도 한 수 배워가는 듯 했습니다!

다음은 리액트 미션이 될텐데 이미 유경험자이신 혜정님께는 생각보다 쉬운 미션이 되겠지만 그만큼 스스로에게 더 엄격하게 프로그래밍을 해보시면 같이 더 발전할 수 있다고 생각해요💯 

이번 미션도 고생하셨고 수정할 부분 최종수정하신 후 머지요청 보내주세요! 감사합니다 ✌🏻

2024-10-05 01:59 UTC, Songhyejeong commented on src/model/BaseballGameModel.js
> +  }
깊은 복사, 얕은 복사에 대한 개념은 공부 했었는데 각각이 어떨 경우에 쓰면 좋은지에 대한 것을 모르고 있었어요,,! 
사실 이 코드는 코드 컨벤션을 지키려고 스프레드 연산자를 사용했는데, 얕은복사에 대해 찾아보니까 '데이터 구조가 간단하고, 중첩된 객체나 배열이 없는 경우에 적합한 방법'이라고 하네요 ! 이 경우에는 얕은 복사가 좋을 거 같네요!

2024-10-05 02:02 UTC, Songhyejeong commented on src/view/BaseballGameView.js
> +  }
예은님 리뷰 반영해서 수정해봤는데 이 방법말고 다른 좋은 방법도 있었을지 모르겠네요..!

2024-10-05 02:22 UTC, Songhyejeong commented on src/model/BaseballGameModel.js
> +    userInput.forEach((userNumber, userIdx) => {
이것도 코드 컨벤션에서 보고 배열 인덱스를 순회할 때, forEach문이 좋을거 같다 생각했습니다 ! !

2024-10-05 02:24 UTC, Songhyejeong commented on src/controller/BaseballGameController.js
> +    this.view.submitButton.addEventListener('click', this.startGame.bind(this));
저도 mvc에 대해서 찾아보다가 bind를 쓴 코드를 보고 참고해봤어요!

2024-10-06 08:37 UTC, merged